// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.2
// source: jzss.proto

package jiuzhang

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// protoc --csharp_out=../Features/Rtb/ --csharp_opt=file_extension=.g.cs jzss.proto
// 请求体
type BidRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 媒体的唯一请求ID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// 本API版本号，例如：1.0.0
	Ver string `protobuf:"bytes,2,opt,name=ver,proto3" json:"ver,omitempty"`
	// 广告位信息
	Imp *BidRequest_Imp `protobuf:"bytes,3,opt,name=imp,proto3" json:"imp,omitempty"`
	// APP信息
	App *BidRequest_App `protobuf:"bytes,4,opt,name=app,proto3" json:"app,omitempty"`
	// 设备信息
	Device *BidRequest_Device `protobuf:"bytes,5,opt,name=device,proto3" json:"device,omitempty"`
	// 用户信息
	User          *BidRequest_User `protobuf:"bytes,6,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidRequest) Reset() {
	*x = BidRequest{}
	mi := &file_jzss_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidRequest) ProtoMessage() {}

func (x *BidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jzss_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidRequest.ProtoReflect.Descriptor instead.
func (*BidRequest) Descriptor() ([]byte, []int) {
	return file_jzss_proto_rawDescGZIP(), []int{0}
}

func (x *BidRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BidRequest) GetVer() string {
	if x != nil {
		return x.Ver
	}
	return ""
}

func (x *BidRequest) GetImp() *BidRequest_Imp {
	if x != nil {
		return x.Imp
	}
	return nil
}

func (x *BidRequest) GetApp() *BidRequest_App {
	if x != nil {
		return x.App
	}
	return nil
}

func (x *BidRequest) GetDevice() *BidRequest_Device {
	if x != nil {
		return x.Device
	}
	return nil
}

func (x *BidRequest) GetUser() *BidRequest_User {
	if x != nil {
		return x.User
	}
	return nil
}

// 请求响应
type BidResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 媒体请求时的唯一ID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// 0 正常参竟 其余值为放弃参竟
	Nbr int32 `protobuf:"varint,2,opt,name=nbr,proto3" json:"nbr,omitempty"`
	// 广告内容信息，无广告返回时此对象为空
	Bid           *BidResponse_Bid `protobuf:"bytes,3,opt,name=bid,proto3" json:"bid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidResponse) Reset() {
	*x = BidResponse{}
	mi := &file_jzss_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidResponse) ProtoMessage() {}

func (x *BidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jzss_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidResponse.ProtoReflect.Descriptor instead.
func (*BidResponse) Descriptor() ([]byte, []int) {
	return file_jzss_proto_rawDescGZIP(), []int{1}
}

func (x *BidResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BidResponse) GetNbr() int32 {
	if x != nil {
		return x.Nbr
	}
	return 0
}

func (x *BidResponse) GetBid() *BidResponse_Bid {
	if x != nil {
		return x.Bid
	}
	return nil
}

type BidRequest_Imp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 广告位ID（联系平台运营人员获取）
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// 广告位宽
	W int32 `protobuf:"varint,2,opt,name=w,proto3" json:"w,omitempty"`
	// 广告位高
	H int32 `protobuf:"varint,3,opt,name=h,proto3" json:"h,omitempty"`
	// 广告类型，1：信息流；2：开屏，3：横幅；4：插屏；5：激励视频；
	Type int32 `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	// 竞价底价，单位: 千次展现/分
	Flr           int32 `protobuf:"varint,5,opt,name=flr,proto3" json:"flr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidRequest_Imp) Reset() {
	*x = BidRequest_Imp{}
	mi := &file_jzss_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidRequest_Imp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidRequest_Imp) ProtoMessage() {}

func (x *BidRequest_Imp) ProtoReflect() protoreflect.Message {
	mi := &file_jzss_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidRequest_Imp.ProtoReflect.Descriptor instead.
func (*BidRequest_Imp) Descriptor() ([]byte, []int) {
	return file_jzss_proto_rawDescGZIP(), []int{0, 0}
}

func (x *BidRequest_Imp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BidRequest_Imp) GetW() int32 {
	if x != nil {
		return x.W
	}
	return 0
}

func (x *BidRequest_Imp) GetH() int32 {
	if x != nil {
		return x.H
	}
	return 0
}

func (x *BidRequest_Imp) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *BidRequest_Imp) GetFlr() int32 {
	if x != nil {
		return x.Flr
	}
	return 0
}

type BidRequest_App struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// APP名称
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// APP包名
	Bundle string `protobuf:"bytes,2,opt,name=bundle,proto3" json:"bundle,omitempty"`
	// APP版本号
	Version       string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidRequest_App) Reset() {
	*x = BidRequest_App{}
	mi := &file_jzss_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidRequest_App) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidRequest_App) ProtoMessage() {}

func (x *BidRequest_App) ProtoReflect() protoreflect.Message {
	mi := &file_jzss_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidRequest_App.ProtoReflect.Descriptor instead.
func (*BidRequest_App) Descriptor() ([]byte, []int) {
	return file_jzss_proto_rawDescGZIP(), []int{0, 1}
}

func (x *BidRequest_App) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BidRequest_App) GetBundle() string {
	if x != nil {
		return x.Bundle
	}
	return ""
}

func (x *BidRequest_App) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type BidRequest_User struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 用户ID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// 用户性别，0：未知，1：男性，2：女性；
	Gender int32 `protobuf:"varint,2,opt,name=gender,proto3" json:"gender,omitempty"`
	// 用户年龄
	Age int32 `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	// 用户画像关键词列表，以逗号分隔
	Keywords      string `protobuf:"bytes,4,opt,name=keywords,proto3" json:"keywords,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidRequest_User) Reset() {
	*x = BidRequest_User{}
	mi := &file_jzss_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidRequest_User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidRequest_User) ProtoMessage() {}

func (x *BidRequest_User) ProtoReflect() protoreflect.Message {
	mi := &file_jzss_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidRequest_User.ProtoReflect.Descriptor instead.
func (*BidRequest_User) Descriptor() ([]byte, []int) {
	return file_jzss_proto_rawDescGZIP(), []int{0, 2}
}

func (x *BidRequest_User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BidRequest_User) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *BidRequest_User) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *BidRequest_User) GetKeywords() string {
	if x != nil {
		return x.Keywords
	}
	return ""
}

type BidRequest_Device struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 设备IP
	Ip string `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	// 设备IPV6
	Ipv6 string `protobuf:"bytes,2,opt,name=ipv6,proto3" json:"ipv6,omitempty"`
	// 设备User-Agent
	Ua string `protobuf:"bytes,3,opt,name=ua,proto3" json:"ua,omitempty"`
	// 设备OS类型，1：Android，2：IOS
	Os int32 `protobuf:"varint,4,opt,name=os,proto3" json:"os,omitempty"`
	// 设备系统版本号，需与UA中的系统版本号一致，例如：8.0.0
	Osv string `protobuf:"bytes,5,opt,name=osv,proto3" json:"osv,omitempty"`
	// 设备类型，0：未知，1：手机，2：平板，3：智能电视；
	DeviceType int32 `protobuf:"varint,6,opt,name=deviceType,proto3" json:"deviceType,omitempty"`
	// 设备经纬度信息
	Geo *BidRequest_Device_Geo `protobuf:"bytes,7,opt,name=geo,proto3" json:"geo,omitempty"`
	// 设备网络信息
	Network *BidRequest_Device_Network `protobuf:"bytes,8,opt,name=network,proto3" json:"network,omitempty"`
	// 设备厂商，例如：Apple、HUAWEI
	Brand string `protobuf:"bytes,9,opt,name=brand,proto3" json:"brand,omitempty"`
	// 设备型号，IOS：Hardware(硬件字符串，例如：iPhone15,2)
	Model string `protobuf:"bytes,10,opt,name=model,proto3" json:"model,omitempty"`
	// 设备型号码，IOS必传(例如：DF12A);
	ModelCode string `protobuf:"bytes,11,opt,name=modelCode,proto3" json:"modelCode,omitempty"`
	// 设备屏幕方向，1：竖屏，2：横屏；
	Orientation int32 `protobuf:"varint,12,opt,name=orientation,proto3" json:"orientation,omitempty"`
	// 设备屏幕(分辨率)宽，例如：1080
	W int32 `protobuf:"varint,13,opt,name=w,proto3" json:"w,omitempty"`
	// 设备屏幕(分辨率)高，例如：1920
	H int32 `protobuf:"varint,14,opt,name=h,proto3" json:"h,omitempty"`
	// 设备屏幕像素密度，例如：2.5
	Dpi float64 `protobuf:"fixed64,15,opt,name=dpi,proto3" json:"dpi,omitempty"`
	// 设备屏幕每英寸像素点数，例如：460
	Ppi int32 `protobuf:"varint,16,opt,name=ppi,proto3" json:"ppi,omitempty"`
	// 设备屏幕尺寸，例如：4.7、5.5英寸
	ScreenSize float64 `protobuf:"fixed64,17,opt,name=screenSize,proto3" json:"screenSize,omitempty"`
	// 设备序列号 Build.SERIAL
	Serialno string `protobuf:"bytes,18,opt,name=serialno,proto3" json:"serialno,omitempty"`
	// Android 设备 ID，Android必传
	AndroidId string `protobuf:"bytes,19,opt,name=androidId,proto3" json:"androidId,omitempty"`
	// Android 设备 ID MD5值
	AndroidIdMd5 string `protobuf:"bytes,20,opt,name=androidIdMd5,proto3" json:"androidIdMd5,omitempty"`
	// Android 设备 imei，Android 10 以下必传
	Imei string `protobuf:"bytes,21,opt,name=imei,proto3" json:"imei,omitempty"`
	// Android 设备 imei MD5值
	ImeiMd5 string `protobuf:"bytes,22,opt,name=imeiMd5,proto3" json:"imeiMd5,omitempty"`
	// ndroid 设备 oaid，Android 10 以上必传
	Oaid string `protobuf:"bytes,23,opt,name=oaid,proto3" json:"oaid,omitempty"`
	// Android 设备 oaid MD5值
	OaidMd5 string `protobuf:"bytes,24,opt,name=oaidMd5,proto3" json:"oaidMd5,omitempty"`
	// droid 设备系统版本，IOS 设备无需此参数
	ApiLevel string `protobuf:"bytes,25,opt,name=apiLevel,proto3" json:"apiLevel,omitempty"`
	// 拼多多PAID，PAID = MD5(设备初始化时间) + "-" + MD5(系统更新时间) + "-" + MD5(系统启动时间)
	Paid string `protobuf:"bytes,26,opt,name=paid,proto3" json:"paid,omitempty"`
	// IOS 设备 idfa，IOS 14 以下必传
	Idfa string `protobuf:"bytes,27,opt,name=idfa,proto3" json:"idfa,omitempty"`
	// IOS 设备 idfa MD5值
	IdfaMd5 string `protobuf:"bytes,28,opt,name=idfaMd5,proto3" json:"idfaMd5,omitempty"`
	// IOS 设备 idfv，IOS必传
	Idfv string `protobuf:"bytes,29,opt,name=idfv,proto3" json:"idfv,omitempty"`
	// IOS 设备 idfv MD5值
	IdfvMd5 string `protobuf:"bytes,30,opt,name=idfvMd5,proto3" json:"idfvMd5,omitempty"`
	// IOS 设备 软件生成替代 UDID 的标识
	OpenUdid string `protobuf:"bytes,31,opt,name=openUdid,proto3" json:"openUdid,omitempty"`
	// IOS caid List，14以上必传，新老版本都要传；
	Caids []*BidRequest_Device_Caid `protobuf:"bytes,32,rep,name=caids,proto3" json:"caids,omitempty"`
	// 设备名称(IOS必传，IOS无法获取时，传deviceNameMd5)；
	DeviceName string `protobuf:"bytes,33,opt,name=deviceName,proto3" json:"deviceName,omitempty"`
	// 设备名称 MD5值
	DeviceNameMd5 string `protobuf:"bytes,34,opt,name=deviceNameMd5,proto3" json:"deviceNameMd5,omitempty"`
	// 设备语言，IOS必传，例如：zh-Hans-CN；
	Language string `protobuf:"bytes,35,opt,name=language,proto3" json:"language,omitempty"`
	// 设备国家，IOS必传，例如：CN；
	Country string `protobuf:"bytes,36,opt,name=country,proto3" json:"country,omitempty"`
	// 设备ROM版本
	RomVer string `protobuf:"bytes,37,opt,name=romVer,proto3" json:"romVer,omitempty"`
	// 系统编译时间
	SysComplingTime string `protobuf:"bytes,38,opt,name=sysComplingTime,proto3" json:"sysComplingTime,omitempty"`
	// 系统启动时间，精确到纳秒， 格式：1754632473.958204976，纳秒为9位
	BootTimeNano string `protobuf:"bytes,39,opt,name=bootTimeNano,proto3" json:"bootTimeNano,omitempty"`
	// 系统更新时间，精确到纳秒， 格式：1754632473.958204976，纳秒为9位
	UpdateTimeNano string `protobuf:"bytes,40,opt,name=updateTimeNano,proto3" json:"updateTimeNano,omitempty"`
	// 设备初始化时间，例如：1754632473.958204976
	SysInitTime string `protobuf:"bytes,41,opt,name=sysInitTime,proto3" json:"sysInitTime,omitempty"`
	// 设备磁盘大小，单位：byte，例如：1099511627776；
	DiskSize int64 `protobuf:"zigzag64,42,opt,name=diskSize,proto3" json:"diskSize,omitempty"`
	// 设备内存大小，单位：byte，例如：8589934592；
	MemorySize int64 `protobuf:"zigzag64,43,opt,name=memorySize,proto3" json:"memorySize,omitempty"`
	// 电池充电状态，0：未知，1：不充电，2：充电，3：满电；
	BatteryStatus int32 `protobuf:"varint,44,opt,name=batteryStatus,proto3" json:"batteryStatus,omitempty"`
	// 电池电量百分比，例如：70
	BatteryPower int32 `protobuf:"varint,45,opt,name=batteryPower,proto3" json:"batteryPower,omitempty"`
	// 设备CPU个数，例如：8
	CpuNumber int32 `protobuf:"varint,46,opt,name=cpuNumber,proto3" json:"cpuNumber,omitempty"`
	// 设备所处时区，例如：28800；
	TimeZone string `protobuf:"bytes,48,opt,name=timeZone,proto3" json:"timeZone,omitempty"`
	// 设备是否允许获取IDFA，0：未确定，1：受限制，2：被拒绝，3：授权；
	Lmt int32 `protobuf:"varint,49,opt,name=lmt,proto3" json:"lmt,omitempty"`
	// 系统启动标识，例如：
	// IOS：1623815045.970028，
	// Android：ec7f4f33-411a-47bc-8067-744a4e7e0723；
	BootMark string `protobuf:"bytes,51,opt,name=bootMark,proto3" json:"bootMark,omitempty"`
	// 系统更新标识，例如：
	// iOS：1581141691.570419583，
	// Android：1004697.709999999；
	UpdateMark string `protobuf:"bytes,52,opt,name=updateMark,proto3" json:"updateMark,omitempty"`
	// 设备应用商店版本，VIVO、OPPO、HUAWEI必传；
	AppStoreVersion string `protobuf:"bytes,53,opt,name=appStoreVersion,proto3" json:"appStoreVersion,omitempty"`
	// HUAWEI 设备的 HMSCore 版本号
	HmsVersion string `protobuf:"bytes,54,opt,name=hmsVersion,proto3" json:"hmsVersion,omitempty"`
	// 设备已安装的APP包名列表
	InstalledApps []string `protobuf:"bytes,56,rep,name=InstalledApps,proto3" json:"InstalledApps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidRequest_Device) Reset() {
	*x = BidRequest_Device{}
	mi := &file_jzss_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidRequest_Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidRequest_Device) ProtoMessage() {}

func (x *BidRequest_Device) ProtoReflect() protoreflect.Message {
	mi := &file_jzss_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidRequest_Device.ProtoReflect.Descriptor instead.
func (*BidRequest_Device) Descriptor() ([]byte, []int) {
	return file_jzss_proto_rawDescGZIP(), []int{0, 3}
}

func (x *BidRequest_Device) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *BidRequest_Device) GetIpv6() string {
	if x != nil {
		return x.Ipv6
	}
	return ""
}

func (x *BidRequest_Device) GetUa() string {
	if x != nil {
		return x.Ua
	}
	return ""
}

func (x *BidRequest_Device) GetOs() int32 {
	if x != nil {
		return x.Os
	}
	return 0
}

func (x *BidRequest_Device) GetOsv() string {
	if x != nil {
		return x.Osv
	}
	return ""
}

func (x *BidRequest_Device) GetDeviceType() int32 {
	if x != nil {
		return x.DeviceType
	}
	return 0
}

func (x *BidRequest_Device) GetGeo() *BidRequest_Device_Geo {
	if x != nil {
		return x.Geo
	}
	return nil
}

func (x *BidRequest_Device) GetNetwork() *BidRequest_Device_Network {
	if x != nil {
		return x.Network
	}
	return nil
}

func (x *BidRequest_Device) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *BidRequest_Device) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *BidRequest_Device) GetModelCode() string {
	if x != nil {
		return x.ModelCode
	}
	return ""
}

func (x *BidRequest_Device) GetOrientation() int32 {
	if x != nil {
		return x.Orientation
	}
	return 0
}

func (x *BidRequest_Device) GetW() int32 {
	if x != nil {
		return x.W
	}
	return 0
}

func (x *BidRequest_Device) GetH() int32 {
	if x != nil {
		return x.H
	}
	return 0
}

func (x *BidRequest_Device) GetDpi() float64 {
	if x != nil {
		return x.Dpi
	}
	return 0
}

func (x *BidRequest_Device) GetPpi() int32 {
	if x != nil {
		return x.Ppi
	}
	return 0
}

func (x *BidRequest_Device) GetScreenSize() float64 {
	if x != nil {
		return x.ScreenSize
	}
	return 0
}

func (x *BidRequest_Device) GetSerialno() string {
	if x != nil {
		return x.Serialno
	}
	return ""
}

func (x *BidRequest_Device) GetAndroidId() string {
	if x != nil {
		return x.AndroidId
	}
	return ""
}

func (x *BidRequest_Device) GetAndroidIdMd5() string {
	if x != nil {
		return x.AndroidIdMd5
	}
	return ""
}

func (x *BidRequest_Device) GetImei() string {
	if x != nil {
		return x.Imei
	}
	return ""
}

func (x *BidRequest_Device) GetImeiMd5() string {
	if x != nil {
		return x.ImeiMd5
	}
	return ""
}

func (x *BidRequest_Device) GetOaid() string {
	if x != nil {
		return x.Oaid
	}
	return ""
}

func (x *BidRequest_Device) GetOaidMd5() string {
	if x != nil {
		return x.OaidMd5
	}
	return ""
}

func (x *BidRequest_Device) GetApiLevel() string {
	if x != nil {
		return x.ApiLevel
	}
	return ""
}

func (x *BidRequest_Device) GetPaid() string {
	if x != nil {
		return x.Paid
	}
	return ""
}

func (x *BidRequest_Device) GetIdfa() string {
	if x != nil {
		return x.Idfa
	}
	return ""
}

func (x *BidRequest_Device) GetIdfaMd5() string {
	if x != nil {
		return x.IdfaMd5
	}
	return ""
}

func (x *BidRequest_Device) GetIdfv() string {
	if x != nil {
		return x.Idfv
	}
	return ""
}

func (x *BidRequest_Device) GetIdfvMd5() string {
	if x != nil {
		return x.IdfvMd5
	}
	return ""
}

func (x *BidRequest_Device) GetOpenUdid() string {
	if x != nil {
		return x.OpenUdid
	}
	return ""
}

func (x *BidRequest_Device) GetCaids() []*BidRequest_Device_Caid {
	if x != nil {
		return x.Caids
	}
	return nil
}

func (x *BidRequest_Device) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *BidRequest_Device) GetDeviceNameMd5() string {
	if x != nil {
		return x.DeviceNameMd5
	}
	return ""
}

func (x *BidRequest_Device) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *BidRequest_Device) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *BidRequest_Device) GetRomVer() string {
	if x != nil {
		return x.RomVer
	}
	return ""
}

func (x *BidRequest_Device) GetSysComplingTime() string {
	if x != nil {
		return x.SysComplingTime
	}
	return ""
}

func (x *BidRequest_Device) GetBootTimeNano() string {
	if x != nil {
		return x.BootTimeNano
	}
	return ""
}

func (x *BidRequest_Device) GetUpdateTimeNano() string {
	if x != nil {
		return x.UpdateTimeNano
	}
	return ""
}

func (x *BidRequest_Device) GetSysInitTime() string {
	if x != nil {
		return x.SysInitTime
	}
	return ""
}

func (x *BidRequest_Device) GetDiskSize() int64 {
	if x != nil {
		return x.DiskSize
	}
	return 0
}

func (x *BidRequest_Device) GetMemorySize() int64 {
	if x != nil {
		return x.MemorySize
	}
	return 0
}

func (x *BidRequest_Device) GetBatteryStatus() int32 {
	if x != nil {
		return x.BatteryStatus
	}
	return 0
}

func (x *BidRequest_Device) GetBatteryPower() int32 {
	if x != nil {
		return x.BatteryPower
	}
	return 0
}

func (x *BidRequest_Device) GetCpuNumber() int32 {
	if x != nil {
		return x.CpuNumber
	}
	return 0
}

func (x *BidRequest_Device) GetTimeZone() string {
	if x != nil {
		return x.TimeZone
	}
	return ""
}

func (x *BidRequest_Device) GetLmt() int32 {
	if x != nil {
		return x.Lmt
	}
	return 0
}

func (x *BidRequest_Device) GetBootMark() string {
	if x != nil {
		return x.BootMark
	}
	return ""
}

func (x *BidRequest_Device) GetUpdateMark() string {
	if x != nil {
		return x.UpdateMark
	}
	return ""
}

func (x *BidRequest_Device) GetAppStoreVersion() string {
	if x != nil {
		return x.AppStoreVersion
	}
	return ""
}

func (x *BidRequest_Device) GetHmsVersion() string {
	if x != nil {
		return x.HmsVersion
	}
	return ""
}

func (x *BidRequest_Device) GetInstalledApps() []string {
	if x != nil {
		return x.InstalledApps
	}
	return nil
}

type BidRequest_Device_Caid struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// caid ios14替代idfa，例如：pd7e3kf7d1641daa3a940cc364j7wi9f
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// caid 版本，iOS14 以上必填，例如：20230303
	Ver string `protobuf:"bytes,2,opt,name=ver,proto3" json:"ver,omitempty"`
	// caid供应商, 0:热云, 1:信通院, 2:阿里因子AAID
	Vendor        int32 `protobuf:"varint,3,opt,name=vendor,proto3" json:"vendor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidRequest_Device_Caid) Reset() {
	*x = BidRequest_Device_Caid{}
	mi := &file_jzss_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidRequest_Device_Caid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidRequest_Device_Caid) ProtoMessage() {}

func (x *BidRequest_Device_Caid) ProtoReflect() protoreflect.Message {
	mi := &file_jzss_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidRequest_Device_Caid.ProtoReflect.Descriptor instead.
func (*BidRequest_Device_Caid) Descriptor() ([]byte, []int) {
	return file_jzss_proto_rawDescGZIP(), []int{0, 3, 0}
}

func (x *BidRequest_Device_Caid) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BidRequest_Device_Caid) GetVer() string {
	if x != nil {
		return x.Ver
	}
	return ""
}

func (x *BidRequest_Device_Caid) GetVendor() int32 {
	if x != nil {
		return x.Vendor
	}
	return 0
}

type BidRequest_Device_Geo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 纬度
	Lat float64 `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	// 经度
	Lon float64 `protobuf:"fixed64,2,opt,name=lon,proto3" json:"lon,omitempty"`
	// 坐标类型，1：GPS/定位，2：IP地址；
	Type int32 `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	// 国家，例如：CN
	Country string `protobuf:"bytes,4,opt,name=country,proto3" json:"country,omitempty"`
	// 省份
	Province string `protobuf:"bytes,5,opt,name=province,proto3" json:"province,omitempty"`
	// 城市
	City          string `protobuf:"bytes,6,opt,name=city,proto3" json:"city,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidRequest_Device_Geo) Reset() {
	*x = BidRequest_Device_Geo{}
	mi := &file_jzss_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidRequest_Device_Geo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidRequest_Device_Geo) ProtoMessage() {}

func (x *BidRequest_Device_Geo) ProtoReflect() protoreflect.Message {
	mi := &file_jzss_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidRequest_Device_Geo.ProtoReflect.Descriptor instead.
func (*BidRequest_Device_Geo) Descriptor() ([]byte, []int) {
	return file_jzss_proto_rawDescGZIP(), []int{0, 3, 1}
}

func (x *BidRequest_Device_Geo) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *BidRequest_Device_Geo) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *BidRequest_Device_Geo) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *BidRequest_Device_Geo) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *BidRequest_Device_Geo) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *BidRequest_Device_Geo) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

type BidRequest_Device_Network struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 网络类型：0：未知，1：Wifi，2：2G，3：3G，4：4G，5：5G；
	ConType int32 `protobuf:"varint,1,opt,name=conType,proto3" json:"conType,omitempty"`
	// 网络运营商：0：未知，1：中国移动，2：中国联通，3：中国电信；，4：中国铁通；
	Carrier int32 `protobuf:"varint,2,opt,name=carrier,proto3" json:"carrier,omitempty"`
	// IMSI(SIM 卡串号)，获取不到完整的值，请获取前五位，IMSI前五位是 mcc + mnc（不需要权限获取）
	Imsi string `protobuf:"bytes,3,opt,name=imsi,proto3" json:"imsi,omitempty"`
	// MAC 地址，例如：66:61:d5:44:56:e6
	Mac string `protobuf:"bytes,6,opt,name=mac,proto3" json:"mac,omitempty"`
	// MAC MD5值，无法获取MAC地址时，可以传MD5值；
	MacMd5 string `protobuf:"bytes,7,opt,name=macMd5,proto3" json:"macMd5,omitempty"`
	// 无线网SSID名称
	Ssid string `protobuf:"bytes,8,opt,name=ssid,proto3" json:"ssid,omitempty"`
	// wifiMac
	WifiMac       string `protobuf:"bytes,9,opt,name=wifiMac,proto3" json:"wifiMac,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidRequest_Device_Network) Reset() {
	*x = BidRequest_Device_Network{}
	mi := &file_jzss_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidRequest_Device_Network) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidRequest_Device_Network) ProtoMessage() {}

func (x *BidRequest_Device_Network) ProtoReflect() protoreflect.Message {
	mi := &file_jzss_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidRequest_Device_Network.ProtoReflect.Descriptor instead.
func (*BidRequest_Device_Network) Descriptor() ([]byte, []int) {
	return file_jzss_proto_rawDescGZIP(), []int{0, 3, 2}
}

func (x *BidRequest_Device_Network) GetConType() int32 {
	if x != nil {
		return x.ConType
	}
	return 0
}

func (x *BidRequest_Device_Network) GetCarrier() int32 {
	if x != nil {
		return x.Carrier
	}
	return 0
}

func (x *BidRequest_Device_Network) GetImsi() string {
	if x != nil {
		return x.Imsi
	}
	return ""
}

func (x *BidRequest_Device_Network) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *BidRequest_Device_Network) GetMacMd5() string {
	if x != nil {
		return x.MacMd5
	}
	return ""
}

func (x *BidRequest_Device_Network) GetSsid() string {
	if x != nil {
		return x.Ssid
	}
	return ""
}

func (x *BidRequest_Device_Network) GetWifiMac() string {
	if x != nil {
		return x.WifiMac
	}
	return ""
}

type BidResponse_Bid struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 竞价唯一ID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// 广告位ID
	SlotId string `protobuf:"bytes,2,opt,name=slotId,proto3" json:"slotId,omitempty"`
	// 广告的类型，1：图文，2：视频；
	CreativeType int32 `protobuf:"varint,3,opt,name=creativeType,proto3" json:"creativeType,omitempty"`
	// 广告的交互类型，1：打开网页(包含deeplink)，2:直接下载应用
	InteractionType int32 `protobuf:"varint,4,opt,name=interactionType,proto3" json:"interactionType,omitempty"`
	// 广告标题
	Title string `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	// 广告描述
	Desc string `protobuf:"bytes,6,opt,name=desc,proto3" json:"desc,omitempty"`
	// 广告图标icon链接
	IconUrl string `protobuf:"bytes,7,opt,name=iconUrl,proto3" json:"iconUrl,omitempty"`
	// 广告图片链接，单个广告可能多个图片地址
	ImgUrls []string `protobuf:"bytes,8,rep,name=imgUrls,proto3" json:"imgUrls,omitempty"`
	// 广告素材图片宽度
	W int32 `protobuf:"varint,9,opt,name=w,proto3" json:"w,omitempty"`
	// 广告素材图片高度
	H int32 `protobuf:"varint,10,opt,name=h,proto3" json:"h,omitempty"`
	// 落地页链接，若 interactionType=2 时，该字段值可能为下载地址，与 downloadUrl 相同；
	TargetUrl string `protobuf:"bytes,11,opt,name=targetUrl,proto3" json:"targetUrl,omitempty"`
	// deeplink链接，该参数有值时，请优先处理，若无值，则处理 targetUrl
	Deeplink string `protobuf:"bytes,12,opt,name=deeplink,proto3" json:"deeplink,omitempty"`
	// iOS系统 deeplink链接，优先级高于deeplink；
	UniversalLink string `protobuf:"bytes,13,opt,name=universalLink,proto3" json:"universalLink,omitempty"`
	// 广告来源
	Source string `protobuf:"bytes,14,opt,name=source,proto3" json:"source,omitempty"`
	// 竞价成功上报地址，需要替换url里边包含的宏
	Nurl []string `protobuf:"bytes,15,rep,name=nurl,proto3" json:"nurl,omitempty"`
	// 竞价失败上报地址，需要替换url里边包含的宏
	Lurl []string `protobuf:"bytes,16,rep,name=lurl,proto3" json:"lurl,omitempty"`
	// 曝光事件上报地址，需要替换url里边包含的宏
	ImpUrls []string `protobuf:"bytes,17,rep,name=impUrls,proto3" json:"impUrls,omitempty"`
	// 点击事件上报地址，需要替换url里边包含的宏
	ClickUrls []string `protobuf:"bytes,18,rep,name=clickUrls,proto3" json:"clickUrls,omitempty"`
	// Deeplink尝试唤醒上报地址，需要替换url里边包含的宏
	DpTryUrls []string `protobuf:"bytes,19,rep,name=dpTryUrls,proto3" json:"dpTryUrls,omitempty"`
	// Deeplink唤醒成功上报地址，需要替换url里边包含的宏
	DpSuccessUrls []string `protobuf:"bytes,20,rep,name=dpSuccessUrls,proto3" json:"dpSuccessUrls,omitempty"`
	// Deeplink唤醒失败上报地址，需要替换url里边包含的宏
	DpFailUrls []string `protobuf:"bytes,21,rep,name=dpFailUrls,proto3" json:"dpFailUrls,omitempty"`
	// 微信开发者APPID
	WechatAppId string `protobuf:"bytes,22,opt,name=wechatAppId,proto3" json:"wechatAppId,omitempty"`
	// 微信小程序原始ID
	WechatOriginId string `protobuf:"bytes,23,opt,name=wechatOriginId,proto3" json:"wechatOriginId,omitempty"`
	// 微信拉起小程序页面的可带参数路径；
	WechatPath string `protobuf:"bytes,24,opt,name=wechatPath,proto3" json:"wechatPath,omitempty"`
	// 竞价广告出价，单位: 千次展现/分
	Price int32 `protobuf:"varint,25,opt,name=price,proto3" json:"price,omitempty"`
	// APP应用下载信息
	App *BidResponse_Bid_App `protobuf:"bytes,26,opt,name=app,proto3" json:"app,omitempty"`
	// 视频广告素材
	Video         *BidResponse_Bid_Video `protobuf:"bytes,27,opt,name=video,proto3" json:"video,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidResponse_Bid) Reset() {
	*x = BidResponse_Bid{}
	mi := &file_jzss_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidResponse_Bid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidResponse_Bid) ProtoMessage() {}

func (x *BidResponse_Bid) ProtoReflect() protoreflect.Message {
	mi := &file_jzss_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidResponse_Bid.ProtoReflect.Descriptor instead.
func (*BidResponse_Bid) Descriptor() ([]byte, []int) {
	return file_jzss_proto_rawDescGZIP(), []int{1, 0}
}

func (x *BidResponse_Bid) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BidResponse_Bid) GetSlotId() string {
	if x != nil {
		return x.SlotId
	}
	return ""
}

func (x *BidResponse_Bid) GetCreativeType() int32 {
	if x != nil {
		return x.CreativeType
	}
	return 0
}

func (x *BidResponse_Bid) GetInteractionType() int32 {
	if x != nil {
		return x.InteractionType
	}
	return 0
}

func (x *BidResponse_Bid) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BidResponse_Bid) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *BidResponse_Bid) GetIconUrl() string {
	if x != nil {
		return x.IconUrl
	}
	return ""
}

func (x *BidResponse_Bid) GetImgUrls() []string {
	if x != nil {
		return x.ImgUrls
	}
	return nil
}

func (x *BidResponse_Bid) GetW() int32 {
	if x != nil {
		return x.W
	}
	return 0
}

func (x *BidResponse_Bid) GetH() int32 {
	if x != nil {
		return x.H
	}
	return 0
}

func (x *BidResponse_Bid) GetTargetUrl() string {
	if x != nil {
		return x.TargetUrl
	}
	return ""
}

func (x *BidResponse_Bid) GetDeeplink() string {
	if x != nil {
		return x.Deeplink
	}
	return ""
}

func (x *BidResponse_Bid) GetUniversalLink() string {
	if x != nil {
		return x.UniversalLink
	}
	return ""
}

func (x *BidResponse_Bid) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *BidResponse_Bid) GetNurl() []string {
	if x != nil {
		return x.Nurl
	}
	return nil
}

func (x *BidResponse_Bid) GetLurl() []string {
	if x != nil {
		return x.Lurl
	}
	return nil
}

func (x *BidResponse_Bid) GetImpUrls() []string {
	if x != nil {
		return x.ImpUrls
	}
	return nil
}

func (x *BidResponse_Bid) GetClickUrls() []string {
	if x != nil {
		return x.ClickUrls
	}
	return nil
}

func (x *BidResponse_Bid) GetDpTryUrls() []string {
	if x != nil {
		return x.DpTryUrls
	}
	return nil
}

func (x *BidResponse_Bid) GetDpSuccessUrls() []string {
	if x != nil {
		return x.DpSuccessUrls
	}
	return nil
}

func (x *BidResponse_Bid) GetDpFailUrls() []string {
	if x != nil {
		return x.DpFailUrls
	}
	return nil
}

func (x *BidResponse_Bid) GetWechatAppId() string {
	if x != nil {
		return x.WechatAppId
	}
	return ""
}

func (x *BidResponse_Bid) GetWechatOriginId() string {
	if x != nil {
		return x.WechatOriginId
	}
	return ""
}

func (x *BidResponse_Bid) GetWechatPath() string {
	if x != nil {
		return x.WechatPath
	}
	return ""
}

func (x *BidResponse_Bid) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *BidResponse_Bid) GetApp() *BidResponse_Bid_App {
	if x != nil {
		return x.App
	}
	return nil
}

func (x *BidResponse_Bid) GetVideo() *BidResponse_Bid_Video {
	if x != nil {
		return x.Video
	}
	return nil
}

type BidResponse_Bid_App struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// APP应用下载链接
	DownloadUrl string `protobuf:"bytes,1,opt,name=downloadUrl,proto3" json:"downloadUrl,omitempty"`
	// 应用名称
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// 应用包名
	Bundle string `protobuf:"bytes,3,opt,name=bundle,proto3" json:"bundle,omitempty"`
	// 应用版本号
	Version string `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	// 应用包大小，单位：kb
	Size int32 `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	// 应用开发者
	Developer string `protobuf:"bytes,6,opt,name=developer,proto3" json:"developer,omitempty"`
	// 应用隐私说明链接
	PrivacyUrl string `protobuf:"bytes,7,opt,name=privacyUrl,proto3" json:"privacyUrl,omitempty"`
	// 应用权限链接
	PermissionUrl string `protobuf:"bytes,8,opt,name=permissionUrl,proto3" json:"permissionUrl,omitempty"`
	// 应用功能说明链接
	FunctionDescUrl string `protobuf:"bytes,9,opt,name=functionDescUrl,proto3" json:"functionDescUrl,omitempty"`
	// 下载开始事件上报地址，需要替换url里边包含的宏
	StartDownloadUrls []string `protobuf:"bytes,10,rep,name=startDownloadUrls,proto3" json:"startDownloadUrls,omitempty"`
	// 下载成功事件上报地址，需要替换url里边包含的宏
	SuccessDownloadUrls []string `protobuf:"bytes,11,rep,name=successDownloadUrls,proto3" json:"successDownloadUrls,omitempty"`
	// 安装开始事件上报地址，需要替换url里边包含的宏
	InstallStartUrls []string `protobuf:"bytes,12,rep,name=installStartUrls,proto3" json:"installStartUrls,omitempty"`
	// 安装成功事件上报地址，需要替换url里边包含的宏
	InstallSuccessUrls []string `protobuf:"bytes,13,rep,name=installSuccessUrls,proto3" json:"installSuccessUrls,omitempty"`
	// 激活成功事件上报地址，需要替换url里边包含的宏
	ActiveSuccessUrls []string `protobuf:"bytes,14,rep,name=activeSuccessUrls,proto3" json:"activeSuccessUrls,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *BidResponse_Bid_App) Reset() {
	*x = BidResponse_Bid_App{}
	mi := &file_jzss_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidResponse_Bid_App) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidResponse_Bid_App) ProtoMessage() {}

func (x *BidResponse_Bid_App) ProtoReflect() protoreflect.Message {
	mi := &file_jzss_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidResponse_Bid_App.ProtoReflect.Descriptor instead.
func (*BidResponse_Bid_App) Descriptor() ([]byte, []int) {
	return file_jzss_proto_rawDescGZIP(), []int{1, 0, 0}
}

func (x *BidResponse_Bid_App) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

func (x *BidResponse_Bid_App) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BidResponse_Bid_App) GetBundle() string {
	if x != nil {
		return x.Bundle
	}
	return ""
}

func (x *BidResponse_Bid_App) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *BidResponse_Bid_App) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *BidResponse_Bid_App) GetDeveloper() string {
	if x != nil {
		return x.Developer
	}
	return ""
}

func (x *BidResponse_Bid_App) GetPrivacyUrl() string {
	if x != nil {
		return x.PrivacyUrl
	}
	return ""
}

func (x *BidResponse_Bid_App) GetPermissionUrl() string {
	if x != nil {
		return x.PermissionUrl
	}
	return ""
}

func (x *BidResponse_Bid_App) GetFunctionDescUrl() string {
	if x != nil {
		return x.FunctionDescUrl
	}
	return ""
}

func (x *BidResponse_Bid_App) GetStartDownloadUrls() []string {
	if x != nil {
		return x.StartDownloadUrls
	}
	return nil
}

func (x *BidResponse_Bid_App) GetSuccessDownloadUrls() []string {
	if x != nil {
		return x.SuccessDownloadUrls
	}
	return nil
}

func (x *BidResponse_Bid_App) GetInstallStartUrls() []string {
	if x != nil {
		return x.InstallStartUrls
	}
	return nil
}

func (x *BidResponse_Bid_App) GetInstallSuccessUrls() []string {
	if x != nil {
		return x.InstallSuccessUrls
	}
	return nil
}

func (x *BidResponse_Bid_App) GetActiveSuccessUrls() []string {
	if x != nil {
		return x.ActiveSuccessUrls
	}
	return nil
}

type BidResponse_Bid_Video struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 视频地址URL
	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	// 视频时长，单位：秒
	Duration int32 `protobuf:"varint,2,opt,name=duration,proto3" json:"duration,omitempty"`
	// 视频体积，单位：byte
	Size int64 `protobuf:"zigzag64,3,opt,name=size,proto3" json:"size,omitempty"`
	// 视频宽度
	W int32 `protobuf:"varint,4,opt,name=w,proto3" json:"w,omitempty"`
	// 视频高度
	H int32 `protobuf:"varint,5,opt,name=h,proto3" json:"h,omitempty"`
	// 视频封面图链接
	CoverUrl string `protobuf:"bytes,6,opt,name=coverUrl,proto3" json:"coverUrl,omitempty"`
	// 视频广告开始播放事件上报地址，需要替换url里边包含的宏
	StartUrls []string `protobuf:"bytes,7,rep,name=startUrls,proto3" json:"startUrls,omitempty"`
	// 视频广告播放25%事件上报地址，需要替换url里边包含的宏
	FourthUrls []string `protobuf:"bytes,8,rep,name=fourthUrls,proto3" json:"fourthUrls,omitempty"`
	// 视频广告播放50%事件上报地址，需要替换url里边包含的宏
	HalfUrls []string `protobuf:"bytes,9,rep,name=halfUrls,proto3" json:"halfUrls,omitempty"`
	// 视频广告播放75%事件上报地址，需要替换url里边包含的宏
	ThdUrls []string `protobuf:"bytes,10,rep,name=thdUrls,proto3" json:"thdUrls,omitempty"`
	// 视频广告播放完成事件上报地址，需要替换url里边包含的宏
	EndUrls       []string `protobuf:"bytes,11,rep,name=endUrls,proto3" json:"endUrls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidResponse_Bid_Video) Reset() {
	*x = BidResponse_Bid_Video{}
	mi := &file_jzss_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidResponse_Bid_Video) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidResponse_Bid_Video) ProtoMessage() {}

func (x *BidResponse_Bid_Video) ProtoReflect() protoreflect.Message {
	mi := &file_jzss_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidResponse_Bid_Video.ProtoReflect.Descriptor instead.
func (*BidResponse_Bid_Video) Descriptor() ([]byte, []int) {
	return file_jzss_proto_rawDescGZIP(), []int{1, 0, 1}
}

func (x *BidResponse_Bid_Video) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *BidResponse_Bid_Video) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *BidResponse_Bid_Video) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *BidResponse_Bid_Video) GetW() int32 {
	if x != nil {
		return x.W
	}
	return 0
}

func (x *BidResponse_Bid_Video) GetH() int32 {
	if x != nil {
		return x.H
	}
	return 0
}

func (x *BidResponse_Bid_Video) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *BidResponse_Bid_Video) GetStartUrls() []string {
	if x != nil {
		return x.StartUrls
	}
	return nil
}

func (x *BidResponse_Bid_Video) GetFourthUrls() []string {
	if x != nil {
		return x.FourthUrls
	}
	return nil
}

func (x *BidResponse_Bid_Video) GetHalfUrls() []string {
	if x != nil {
		return x.HalfUrls
	}
	return nil
}

func (x *BidResponse_Bid_Video) GetThdUrls() []string {
	if x != nil {
		return x.ThdUrls
	}
	return nil
}

func (x *BidResponse_Bid_Video) GetEndUrls() []string {
	if x != nil {
		return x.EndUrls
	}
	return nil
}

var File_jzss_proto protoreflect.FileDescriptor

const file_jzss_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"jzss.proto\x12\bjiuzhang\"\xe9\x12\n" +
	"\n" +
	"BidRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03ver\x18\x02 \x01(\tR\x03ver\x12*\n" +
	"\x03imp\x18\x03 \x01(\v2\x18.jiuzhang.BidRequest.ImpR\x03imp\x12*\n" +
	"\x03app\x18\x04 \x01(\v2\x18.jiuzhang.BidRequest.AppR\x03app\x123\n" +
	"\x06device\x18\x05 \x01(\v2\x1b.jiuzhang.BidRequest.DeviceR\x06device\x12-\n" +
	"\x04user\x18\x06 \x01(\v2\x19.jiuzhang.BidRequest.UserR\x04user\x1aW\n" +
	"\x03Imp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\f\n" +
	"\x01w\x18\x02 \x01(\x05R\x01w\x12\f\n" +
	"\x01h\x18\x03 \x01(\x05R\x01h\x12\x12\n" +
	"\x04type\x18\x04 \x01(\x05R\x04type\x12\x10\n" +
	"\x03flr\x18\x05 \x01(\x05R\x03flr\x1aK\n" +
	"\x03App\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06bundle\x18\x02 \x01(\tR\x06bundle\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x1a\\\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06gender\x18\x02 \x01(\x05R\x06gender\x12\x10\n" +
	"\x03age\x18\x03 \x01(\x05R\x03age\x12\x1a\n" +
	"\bkeywords\x18\x04 \x01(\tR\bkeywords\x1a\xf8\x0e\n" +
	"\x06Device\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x12\n" +
	"\x04ipv6\x18\x02 \x01(\tR\x04ipv6\x12\x0e\n" +
	"\x02ua\x18\x03 \x01(\tR\x02ua\x12\x0e\n" +
	"\x02os\x18\x04 \x01(\x05R\x02os\x12\x10\n" +
	"\x03osv\x18\x05 \x01(\tR\x03osv\x12\x1e\n" +
	"\n" +
	"deviceType\x18\x06 \x01(\x05R\n" +
	"deviceType\x121\n" +
	"\x03geo\x18\a \x01(\v2\x1f.jiuzhang.BidRequest.Device.GeoR\x03geo\x12=\n" +
	"\anetwork\x18\b \x01(\v2#.jiuzhang.BidRequest.Device.NetworkR\anetwork\x12\x14\n" +
	"\x05brand\x18\t \x01(\tR\x05brand\x12\x14\n" +
	"\x05model\x18\n" +
	" \x01(\tR\x05model\x12\x1c\n" +
	"\tmodelCode\x18\v \x01(\tR\tmodelCode\x12 \n" +
	"\vorientation\x18\f \x01(\x05R\vorientation\x12\f\n" +
	"\x01w\x18\r \x01(\x05R\x01w\x12\f\n" +
	"\x01h\x18\x0e \x01(\x05R\x01h\x12\x10\n" +
	"\x03dpi\x18\x0f \x01(\x01R\x03dpi\x12\x10\n" +
	"\x03ppi\x18\x10 \x01(\x05R\x03ppi\x12\x1e\n" +
	"\n" +
	"screenSize\x18\x11 \x01(\x01R\n" +
	"screenSize\x12\x1a\n" +
	"\bserialno\x18\x12 \x01(\tR\bserialno\x12\x1c\n" +
	"\tandroidId\x18\x13 \x01(\tR\tandroidId\x12\"\n" +
	"\fandroidIdMd5\x18\x14 \x01(\tR\fandroidIdMd5\x12\x12\n" +
	"\x04imei\x18\x15 \x01(\tR\x04imei\x12\x18\n" +
	"\aimeiMd5\x18\x16 \x01(\tR\aimeiMd5\x12\x12\n" +
	"\x04oaid\x18\x17 \x01(\tR\x04oaid\x12\x18\n" +
	"\aoaidMd5\x18\x18 \x01(\tR\aoaidMd5\x12\x1a\n" +
	"\bapiLevel\x18\x19 \x01(\tR\bapiLevel\x12\x12\n" +
	"\x04paid\x18\x1a \x01(\tR\x04paid\x12\x12\n" +
	"\x04idfa\x18\x1b \x01(\tR\x04idfa\x12\x18\n" +
	"\aidfaMd5\x18\x1c \x01(\tR\aidfaMd5\x12\x12\n" +
	"\x04idfv\x18\x1d \x01(\tR\x04idfv\x12\x18\n" +
	"\aidfvMd5\x18\x1e \x01(\tR\aidfvMd5\x12\x1a\n" +
	"\bopenUdid\x18\x1f \x01(\tR\bopenUdid\x126\n" +
	"\x05caids\x18  \x03(\v2 .jiuzhang.BidRequest.Device.CaidR\x05caids\x12\x1e\n" +
	"\n" +
	"deviceName\x18! \x01(\tR\n" +
	"deviceName\x12$\n" +
	"\rdeviceNameMd5\x18\" \x01(\tR\rdeviceNameMd5\x12\x1a\n" +
	"\blanguage\x18# \x01(\tR\blanguage\x12\x18\n" +
	"\acountry\x18$ \x01(\tR\acountry\x12\x16\n" +
	"\x06romVer\x18% \x01(\tR\x06romVer\x12(\n" +
	"\x0fsysComplingTime\x18& \x01(\tR\x0fsysComplingTime\x12\"\n" +
	"\fbootTimeNano\x18' \x01(\tR\fbootTimeNano\x12&\n" +
	"\x0eupdateTimeNano\x18( \x01(\tR\x0eupdateTimeNano\x12 \n" +
	"\vsysInitTime\x18) \x01(\tR\vsysInitTime\x12\x1a\n" +
	"\bdiskSize\x18* \x01(\x12R\bdiskSize\x12\x1e\n" +
	"\n" +
	"memorySize\x18+ \x01(\x12R\n" +
	"memorySize\x12$\n" +
	"\rbatteryStatus\x18, \x01(\x05R\rbatteryStatus\x12\"\n" +
	"\fbatteryPower\x18- \x01(\x05R\fbatteryPower\x12\x1c\n" +
	"\tcpuNumber\x18. \x01(\x05R\tcpuNumber\x12\x1a\n" +
	"\btimeZone\x180 \x01(\tR\btimeZone\x12\x10\n" +
	"\x03lmt\x181 \x01(\x05R\x03lmt\x12\x1a\n" +
	"\bbootMark\x183 \x01(\tR\bbootMark\x12\x1e\n" +
	"\n" +
	"updateMark\x184 \x01(\tR\n" +
	"updateMark\x12(\n" +
	"\x0fappStoreVersion\x185 \x01(\tR\x0fappStoreVersion\x12\x1e\n" +
	"\n" +
	"hmsVersion\x186 \x01(\tR\n" +
	"hmsVersion\x12$\n" +
	"\rInstalledApps\x188 \x03(\tR\rInstalledApps\x1a@\n" +
	"\x04Caid\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03ver\x18\x02 \x01(\tR\x03ver\x12\x16\n" +
	"\x06vendor\x18\x03 \x01(\x05R\x06vendor\x1a\x87\x01\n" +
	"\x03Geo\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lon\x18\x02 \x01(\x01R\x03lon\x12\x12\n" +
	"\x04type\x18\x03 \x01(\x05R\x04type\x12\x18\n" +
	"\acountry\x18\x04 \x01(\tR\acountry\x12\x1a\n" +
	"\bprovince\x18\x05 \x01(\tR\bprovince\x12\x12\n" +
	"\x04city\x18\x06 \x01(\tR\x04city\x1a\xa9\x01\n" +
	"\aNetwork\x12\x18\n" +
	"\aconType\x18\x01 \x01(\x05R\aconType\x12\x18\n" +
	"\acarrier\x18\x02 \x01(\x05R\acarrier\x12\x12\n" +
	"\x04imsi\x18\x03 \x01(\tR\x04imsi\x12\x10\n" +
	"\x03mac\x18\x06 \x01(\tR\x03mac\x12\x16\n" +
	"\x06macMd5\x18\a \x01(\tR\x06macMd5\x12\x12\n" +
	"\x04ssid\x18\b \x01(\tR\x04ssid\x12\x18\n" +
	"\awifiMac\x18\t \x01(\tR\awifiMac\"\x86\r\n" +
	"\vBidResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03nbr\x18\x02 \x01(\x05R\x03nbr\x12+\n" +
	"\x03bid\x18\x03 \x01(\v2\x19.jiuzhang.BidResponse.BidR\x03bid\x1a\xa7\f\n" +
	"\x03Bid\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06slotId\x18\x02 \x01(\tR\x06slotId\x12\"\n" +
	"\fcreativeType\x18\x03 \x01(\x05R\fcreativeType\x12(\n" +
	"\x0finteractionType\x18\x04 \x01(\x05R\x0finteractionType\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12\x12\n" +
	"\x04desc\x18\x06 \x01(\tR\x04desc\x12\x18\n" +
	"\aiconUrl\x18\a \x01(\tR\aiconUrl\x12\x18\n" +
	"\aimgUrls\x18\b \x03(\tR\aimgUrls\x12\f\n" +
	"\x01w\x18\t \x01(\x05R\x01w\x12\f\n" +
	"\x01h\x18\n" +
	" \x01(\x05R\x01h\x12\x1c\n" +
	"\ttargetUrl\x18\v \x01(\tR\ttargetUrl\x12\x1a\n" +
	"\bdeeplink\x18\f \x01(\tR\bdeeplink\x12$\n" +
	"\runiversalLink\x18\r \x01(\tR\runiversalLink\x12\x16\n" +
	"\x06source\x18\x0e \x01(\tR\x06source\x12\x12\n" +
	"\x04nurl\x18\x0f \x03(\tR\x04nurl\x12\x12\n" +
	"\x04lurl\x18\x10 \x03(\tR\x04lurl\x12\x18\n" +
	"\aimpUrls\x18\x11 \x03(\tR\aimpUrls\x12\x1c\n" +
	"\tclickUrls\x18\x12 \x03(\tR\tclickUrls\x12\x1c\n" +
	"\tdpTryUrls\x18\x13 \x03(\tR\tdpTryUrls\x12$\n" +
	"\rdpSuccessUrls\x18\x14 \x03(\tR\rdpSuccessUrls\x12\x1e\n" +
	"\n" +
	"dpFailUrls\x18\x15 \x03(\tR\n" +
	"dpFailUrls\x12 \n" +
	"\vwechatAppId\x18\x16 \x01(\tR\vwechatAppId\x12&\n" +
	"\x0ewechatOriginId\x18\x17 \x01(\tR\x0ewechatOriginId\x12\x1e\n" +
	"\n" +
	"wechatPath\x18\x18 \x01(\tR\n" +
	"wechatPath\x12\x14\n" +
	"\x05price\x18\x19 \x01(\x05R\x05price\x12/\n" +
	"\x03app\x18\x1a \x01(\v2\x1d.jiuzhang.BidResponse.Bid.AppR\x03app\x125\n" +
	"\x05video\x18\x1b \x01(\v2\x1f.jiuzhang.BidResponse.Bid.VideoR\x05video\x1a\xf9\x03\n" +
	"\x03App\x12 \n" +
	"\vdownloadUrl\x18\x01 \x01(\tR\vdownloadUrl\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06bundle\x18\x03 \x01(\tR\x06bundle\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x12\n" +
	"\x04size\x18\x05 \x01(\x05R\x04size\x12\x1c\n" +
	"\tdeveloper\x18\x06 \x01(\tR\tdeveloper\x12\x1e\n" +
	"\n" +
	"privacyUrl\x18\a \x01(\tR\n" +
	"privacyUrl\x12$\n" +
	"\rpermissionUrl\x18\b \x01(\tR\rpermissionUrl\x12(\n" +
	"\x0ffunctionDescUrl\x18\t \x01(\tR\x0ffunctionDescUrl\x12,\n" +
	"\x11startDownloadUrls\x18\n" +
	" \x03(\tR\x11startDownloadUrls\x120\n" +
	"\x13successDownloadUrls\x18\v \x03(\tR\x13successDownloadUrls\x12*\n" +
	"\x10installStartUrls\x18\f \x03(\tR\x10installStartUrls\x12.\n" +
	"\x12installSuccessUrls\x18\r \x03(\tR\x12installSuccessUrls\x12,\n" +
	"\x11activeSuccessUrls\x18\x0e \x03(\tR\x11activeSuccessUrls\x1a\x8f\x02\n" +
	"\x05Video\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1a\n" +
	"\bduration\x18\x02 \x01(\x05R\bduration\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x12R\x04size\x12\f\n" +
	"\x01w\x18\x04 \x01(\x05R\x01w\x12\f\n" +
	"\x01h\x18\x05 \x01(\x05R\x01h\x12\x1a\n" +
	"\bcoverUrl\x18\x06 \x01(\tR\bcoverUrl\x12\x1c\n" +
	"\tstartUrls\x18\a \x03(\tR\tstartUrls\x12\x1e\n" +
	"\n" +
	"fourthUrls\x18\b \x03(\tR\n" +
	"fourthUrls\x12\x1a\n" +
	"\bhalfUrls\x18\t \x03(\tR\bhalfUrls\x12\x18\n" +
	"\athdUrls\x18\n" +
	" \x03(\tR\athdUrls\x12\x18\n" +
	"\aendUrls\x18\v \x03(\tR\aendUrlsB\rZ\v./;jiuzhangb\x06proto3"

var (
	file_jzss_proto_rawDescOnce sync.Once
	file_jzss_proto_rawDescData []byte
)

func file_jzss_proto_rawDescGZIP() []byte {
	file_jzss_proto_rawDescOnce.Do(func() {
		file_jzss_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_jzss_proto_rawDesc), len(file_jzss_proto_rawDesc)))
	})
	return file_jzss_proto_rawDescData
}

var file_jzss_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_jzss_proto_goTypes = []any{
	(*BidRequest)(nil),                // 0: jiuzhang.BidRequest
	(*BidResponse)(nil),               // 1: jiuzhang.BidResponse
	(*BidRequest_Imp)(nil),            // 2: jiuzhang.BidRequest.Imp
	(*BidRequest_App)(nil),            // 3: jiuzhang.BidRequest.App
	(*BidRequest_User)(nil),           // 4: jiuzhang.BidRequest.User
	(*BidRequest_Device)(nil),         // 5: jiuzhang.BidRequest.Device
	(*BidRequest_Device_Caid)(nil),    // 6: jiuzhang.BidRequest.Device.Caid
	(*BidRequest_Device_Geo)(nil),     // 7: jiuzhang.BidRequest.Device.Geo
	(*BidRequest_Device_Network)(nil), // 8: jiuzhang.BidRequest.Device.Network
	(*BidResponse_Bid)(nil),           // 9: jiuzhang.BidResponse.Bid
	(*BidResponse_Bid_App)(nil),       // 10: jiuzhang.BidResponse.Bid.App
	(*BidResponse_Bid_Video)(nil),     // 11: jiuzhang.BidResponse.Bid.Video
}
var file_jzss_proto_depIdxs = []int32{
	2,  // 0: jiuzhang.BidRequest.imp:type_name -> jiuzhang.BidRequest.Imp
	3,  // 1: jiuzhang.BidRequest.app:type_name -> jiuzhang.BidRequest.App
	5,  // 2: jiuzhang.BidRequest.device:type_name -> jiuzhang.BidRequest.Device
	4,  // 3: jiuzhang.BidRequest.user:type_name -> jiuzhang.BidRequest.User
	9,  // 4: jiuzhang.BidResponse.bid:type_name -> jiuzhang.BidResponse.Bid
	7,  // 5: jiuzhang.BidRequest.Device.geo:type_name -> jiuzhang.BidRequest.Device.Geo
	8,  // 6: jiuzhang.BidRequest.Device.network:type_name -> jiuzhang.BidRequest.Device.Network
	6,  // 7: jiuzhang.BidRequest.Device.caids:type_name -> jiuzhang.BidRequest.Device.Caid
	10, // 8: jiuzhang.BidResponse.Bid.app:type_name -> jiuzhang.BidResponse.Bid.App
	11, // 9: jiuzhang.BidResponse.Bid.video:type_name -> jiuzhang.BidResponse.Bid.Video
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_jzss_proto_init() }
func file_jzss_proto_init() {
	if File_jzss_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_jzss_proto_rawDesc), len(file_jzss_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_jzss_proto_goTypes,
		DependencyIndexes: file_jzss_proto_depIdxs,
		MessageInfos:      file_jzss_proto_msgTypes,
	}.Build()
	File_jzss_proto = out.File
	file_jzss_proto_goTypes = nil
	file_jzss_proto_depIdxs = nil
}
