// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.2
// source: jiuzhu.proto

package jiuzhu

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JZRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Ver                string                 `protobuf:"bytes,2,opt,name=ver,proto3" json:"ver,omitempty"`
	AdId               string                 `protobuf:"bytes,3,opt,name=ad_id,json=adId,proto3" json:"ad_id,omitempty"`
	AdWidth            int32                  `protobuf:"varint,4,opt,name=ad_width,json=adWidth,proto3" json:"ad_width,omitempty"`
	AdHeight           int32                  `protobuf:"varint,5,opt,name=ad_height,json=adHeight,proto3" json:"ad_height,omitempty"`
	AppName            string                 `protobuf:"bytes,6,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	PkgName            string                 `protobuf:"bytes,7,opt,name=pkg_name,json=pkgName,proto3" json:"pkg_name,omitempty"`
	Apv                string                 `protobuf:"bytes,8,opt,name=apv,proto3" json:"apv,omitempty"`
	Make               string                 `protobuf:"bytes,9,opt,name=make,proto3" json:"make,omitempty"`
	Brand              string                 `protobuf:"bytes,10,opt,name=brand,proto3" json:"brand,omitempty"`
	Model              string                 `protobuf:"bytes,11,opt,name=model,proto3" json:"model,omitempty"`
	Density            float64                `protobuf:"fixed64,12,opt,name=density,proto3" json:"density,omitempty"`
	Os                 int32                  `protobuf:"varint,13,opt,name=os,proto3" json:"os,omitempty"`
	OsVer              string                 `protobuf:"bytes,14,opt,name=os_ver,json=osVer,proto3" json:"os_ver,omitempty"`
	ApiLevel           int32                  `protobuf:"varint,15,opt,name=api_level,json=apiLevel,proto3" json:"api_level,omitempty"`
	DevWidth           int32                  `protobuf:"varint,16,opt,name=dev_width,json=devWidth,proto3" json:"dev_width,omitempty"`
	DevHeight          int32                  `protobuf:"varint,17,opt,name=dev_height,json=devHeight,proto3" json:"dev_height,omitempty"`
	DevOrient          int32                  `protobuf:"varint,18,opt,name=dev_orient,json=devOrient,proto3" json:"dev_orient,omitempty"`
	AppstoreVer        string                 `protobuf:"bytes,19,opt,name=appstore_ver,json=appstoreVer,proto3" json:"appstore_ver,omitempty"`
	Hmscore            string                 `protobuf:"bytes,20,opt,name=hmscore,proto3" json:"hmscore,omitempty"`
	UiVer              string                 `protobuf:"bytes,21,opt,name=ui_ver,json=uiVer,proto3" json:"ui_ver,omitempty"`
	DevType            int32                  `protobuf:"varint,22,opt,name=dev_type,json=devType,proto3" json:"dev_type,omitempty"`
	Carrier            int32                  `protobuf:"varint,23,opt,name=carrier,proto3" json:"carrier,omitempty"`
	OperatorNop        string                 `protobuf:"bytes,24,opt,name=operator_nop,json=operatorNop,proto3" json:"operator_nop,omitempty"`
	NetType            int32                  `protobuf:"varint,25,opt,name=net_type,json=netType,proto3" json:"net_type,omitempty"`
	Imsi               string                 `protobuf:"bytes,26,opt,name=imsi,proto3" json:"imsi,omitempty"`
	Mac                string                 `protobuf:"bytes,27,opt,name=mac,proto3" json:"mac,omitempty"`
	BidPrice           int32                  `protobuf:"varint,28,opt,name=bid_price,json=bidPrice,proto3" json:"bid_price,omitempty"`
	Imei               string                 `protobuf:"bytes,29,opt,name=imei,proto3" json:"imei,omitempty"`
	ImeiMd5            string                 `protobuf:"bytes,30,opt,name=imei_md5,json=imeiMd5,proto3" json:"imei_md5,omitempty"`
	AndroidId          string                 `protobuf:"bytes,31,opt,name=android_id,json=androidId,proto3" json:"android_id,omitempty"`
	Oaid               string                 `protobuf:"bytes,32,opt,name=oaid,proto3" json:"oaid,omitempty"`
	UserAgent          string                 `protobuf:"bytes,33,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	Idfa               string                 `protobuf:"bytes,34,opt,name=idfa,proto3" json:"idfa,omitempty"`
	IdfaMd5            string                 `protobuf:"bytes,35,opt,name=idfa_md5,json=idfaMd5,proto3" json:"idfa_md5,omitempty"`
	Idfv               string                 `protobuf:"bytes,36,opt,name=idfv,proto3" json:"idfv,omitempty"`
	Caid               string                 `protobuf:"bytes,37,opt,name=caid,proto3" json:"caid,omitempty"`
	CaidVer            string                 `protobuf:"bytes,38,opt,name=caid_ver,json=caidVer,proto3" json:"caid_ver,omitempty"`
	Udid               string                 `protobuf:"bytes,39,opt,name=udid,proto3" json:"udid,omitempty"`
	Ip                 string                 `protobuf:"bytes,40,opt,name=ip,proto3" json:"ip,omitempty"`
	Ipv6               string                 `protobuf:"bytes,41,opt,name=ipv6,proto3" json:"ipv6,omitempty"`
	Ppi                int32                  `protobuf:"varint,42,opt,name=ppi,proto3" json:"ppi,omitempty"`
	Lon                string                 `protobuf:"bytes,43,opt,name=lon,proto3" json:"lon,omitempty"`
	Lat                string                 `protobuf:"bytes,44,opt,name=lat,proto3" json:"lat,omitempty"`
	BootMark           string                 `protobuf:"bytes,45,opt,name=boot_mark,json=bootMark,proto3" json:"boot_mark,omitempty"`
	UpdateMark         string                 `protobuf:"bytes,46,opt,name=update_mark,json=updateMark,proto3" json:"update_mark,omitempty"`
	Serialno           string                 `protobuf:"bytes,47,opt,name=serialno,proto3" json:"serialno,omitempty"`
	RomVer             string                 `protobuf:"bytes,48,opt,name=rom_ver,json=romVer,proto3" json:"rom_ver,omitempty"`
	SysCompilingTime   string                 `protobuf:"bytes,49,opt,name=sys_compiling_time,json=sysCompilingTime,proto3" json:"sys_compiling_time,omitempty"`
	DevNameMd5         string                 `protobuf:"bytes,50,opt,name=dev_name_md5,json=devNameMd5,proto3" json:"dev_name_md5,omitempty"`
	StartupTime        string                 `protobuf:"bytes,51,opt,name=startup_time,json=startupTime,proto3" json:"startup_time,omitempty"`
	UpgradeTime        string                 `protobuf:"bytes,52,opt,name=upgrade_time,json=upgradeTime,proto3" json:"upgrade_time,omitempty"`
	SysStartUpNanoTime string                 `protobuf:"bytes,53,opt,name=sys_start_up_nano_time,json=sysStartUpNanoTime,proto3" json:"sys_start_up_nano_time,omitempty"`
	SysUpdateNanoTime  string                 `protobuf:"bytes,54,opt,name=sys_update_nano_time,json=sysUpdateNanoTime,proto3" json:"sys_update_nano_time,omitempty"`
	DevInitNanoTime    string                 `protobuf:"bytes,55,opt,name=dev_init_nano_time,json=devInitNanoTime,proto3" json:"dev_init_nano_time,omitempty"`
	Timezone           string                 `protobuf:"bytes,56,opt,name=timezone,proto3" json:"timezone,omitempty"`
	HardwareModel      string                 `protobuf:"bytes,57,opt,name=hardware_model,json=hardwareModel,proto3" json:"hardware_model,omitempty"`
	Memory             int64                  `protobuf:"varint,58,opt,name=memory,proto3" json:"memory,omitempty"`
	HardDisk           int64                  `protobuf:"varint,59,opt,name=hard_disk,json=hardDisk,proto3" json:"hard_disk,omitempty"`
	CpuNum             int32                  `protobuf:"varint,60,opt,name=cpu_num,json=cpuNum,proto3" json:"cpu_num,omitempty"`
	CpuFreq            float64                `protobuf:"fixed64,61,opt,name=cpu_freq,json=cpuFreq,proto3" json:"cpu_freq,omitempty"`
	IdfaPolicy         int32                  `protobuf:"varint,62,opt,name=idfa_policy,json=idfaPolicy,proto3" json:"idfa_policy,omitempty"`
	BatteryStatus      int32                  `protobuf:"varint,63,opt,name=battery_status,json=batteryStatus,proto3" json:"battery_status,omitempty"`
	BatteryPower       int32                  `protobuf:"varint,64,opt,name=battery_power,json=batteryPower,proto3" json:"battery_power,omitempty"`
	DevFileTime        string                 `protobuf:"bytes,65,opt,name=dev_file_time,json=devFileTime,proto3" json:"dev_file_time,omitempty"`
	CountryCode        string                 `protobuf:"bytes,66,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	Language           string                 `protobuf:"bytes,67,opt,name=language,proto3" json:"language,omitempty"`
	Paid               string                 `protobuf:"bytes,68,opt,name=paid,proto3" json:"paid,omitempty"`
	Pkgs               []string               `protobuf:"bytes,69,rep,name=pkgs,proto3" json:"pkgs,omitempty"`
	Caids              []*JZRequest_Caid      `protobuf:"bytes,70,rep,name=caids,proto3" json:"caids,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *JZRequest) Reset() {
	*x = JZRequest{}
	mi := &file_jiuzhu_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JZRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JZRequest) ProtoMessage() {}

func (x *JZRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jiuzhu_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JZRequest.ProtoReflect.Descriptor instead.
func (*JZRequest) Descriptor() ([]byte, []int) {
	return file_jiuzhu_proto_rawDescGZIP(), []int{0}
}

func (x *JZRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *JZRequest) GetVer() string {
	if x != nil {
		return x.Ver
	}
	return ""
}

func (x *JZRequest) GetAdId() string {
	if x != nil {
		return x.AdId
	}
	return ""
}

func (x *JZRequest) GetAdWidth() int32 {
	if x != nil {
		return x.AdWidth
	}
	return 0
}

func (x *JZRequest) GetAdHeight() int32 {
	if x != nil {
		return x.AdHeight
	}
	return 0
}

func (x *JZRequest) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *JZRequest) GetPkgName() string {
	if x != nil {
		return x.PkgName
	}
	return ""
}

func (x *JZRequest) GetApv() string {
	if x != nil {
		return x.Apv
	}
	return ""
}

func (x *JZRequest) GetMake() string {
	if x != nil {
		return x.Make
	}
	return ""
}

func (x *JZRequest) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *JZRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *JZRequest) GetDensity() float64 {
	if x != nil {
		return x.Density
	}
	return 0
}

func (x *JZRequest) GetOs() int32 {
	if x != nil {
		return x.Os
	}
	return 0
}

func (x *JZRequest) GetOsVer() string {
	if x != nil {
		return x.OsVer
	}
	return ""
}

func (x *JZRequest) GetApiLevel() int32 {
	if x != nil {
		return x.ApiLevel
	}
	return 0
}

func (x *JZRequest) GetDevWidth() int32 {
	if x != nil {
		return x.DevWidth
	}
	return 0
}

func (x *JZRequest) GetDevHeight() int32 {
	if x != nil {
		return x.DevHeight
	}
	return 0
}

func (x *JZRequest) GetDevOrient() int32 {
	if x != nil {
		return x.DevOrient
	}
	return 0
}

func (x *JZRequest) GetAppstoreVer() string {
	if x != nil {
		return x.AppstoreVer
	}
	return ""
}

func (x *JZRequest) GetHmscore() string {
	if x != nil {
		return x.Hmscore
	}
	return ""
}

func (x *JZRequest) GetUiVer() string {
	if x != nil {
		return x.UiVer
	}
	return ""
}

func (x *JZRequest) GetDevType() int32 {
	if x != nil {
		return x.DevType
	}
	return 0
}

func (x *JZRequest) GetCarrier() int32 {
	if x != nil {
		return x.Carrier
	}
	return 0
}

func (x *JZRequest) GetOperatorNop() string {
	if x != nil {
		return x.OperatorNop
	}
	return ""
}

func (x *JZRequest) GetNetType() int32 {
	if x != nil {
		return x.NetType
	}
	return 0
}

func (x *JZRequest) GetImsi() string {
	if x != nil {
		return x.Imsi
	}
	return ""
}

func (x *JZRequest) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *JZRequest) GetBidPrice() int32 {
	if x != nil {
		return x.BidPrice
	}
	return 0
}

func (x *JZRequest) GetImei() string {
	if x != nil {
		return x.Imei
	}
	return ""
}

func (x *JZRequest) GetImeiMd5() string {
	if x != nil {
		return x.ImeiMd5
	}
	return ""
}

func (x *JZRequest) GetAndroidId() string {
	if x != nil {
		return x.AndroidId
	}
	return ""
}

func (x *JZRequest) GetOaid() string {
	if x != nil {
		return x.Oaid
	}
	return ""
}

func (x *JZRequest) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *JZRequest) GetIdfa() string {
	if x != nil {
		return x.Idfa
	}
	return ""
}

func (x *JZRequest) GetIdfaMd5() string {
	if x != nil {
		return x.IdfaMd5
	}
	return ""
}

func (x *JZRequest) GetIdfv() string {
	if x != nil {
		return x.Idfv
	}
	return ""
}

func (x *JZRequest) GetCaid() string {
	if x != nil {
		return x.Caid
	}
	return ""
}

func (x *JZRequest) GetCaidVer() string {
	if x != nil {
		return x.CaidVer
	}
	return ""
}

func (x *JZRequest) GetUdid() string {
	if x != nil {
		return x.Udid
	}
	return ""
}

func (x *JZRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *JZRequest) GetIpv6() string {
	if x != nil {
		return x.Ipv6
	}
	return ""
}

func (x *JZRequest) GetPpi() int32 {
	if x != nil {
		return x.Ppi
	}
	return 0
}

func (x *JZRequest) GetLon() string {
	if x != nil {
		return x.Lon
	}
	return ""
}

func (x *JZRequest) GetLat() string {
	if x != nil {
		return x.Lat
	}
	return ""
}

func (x *JZRequest) GetBootMark() string {
	if x != nil {
		return x.BootMark
	}
	return ""
}

func (x *JZRequest) GetUpdateMark() string {
	if x != nil {
		return x.UpdateMark
	}
	return ""
}

func (x *JZRequest) GetSerialno() string {
	if x != nil {
		return x.Serialno
	}
	return ""
}

func (x *JZRequest) GetRomVer() string {
	if x != nil {
		return x.RomVer
	}
	return ""
}

func (x *JZRequest) GetSysCompilingTime() string {
	if x != nil {
		return x.SysCompilingTime
	}
	return ""
}

func (x *JZRequest) GetDevNameMd5() string {
	if x != nil {
		return x.DevNameMd5
	}
	return ""
}

func (x *JZRequest) GetStartupTime() string {
	if x != nil {
		return x.StartupTime
	}
	return ""
}

func (x *JZRequest) GetUpgradeTime() string {
	if x != nil {
		return x.UpgradeTime
	}
	return ""
}

func (x *JZRequest) GetSysStartUpNanoTime() string {
	if x != nil {
		return x.SysStartUpNanoTime
	}
	return ""
}

func (x *JZRequest) GetSysUpdateNanoTime() string {
	if x != nil {
		return x.SysUpdateNanoTime
	}
	return ""
}

func (x *JZRequest) GetDevInitNanoTime() string {
	if x != nil {
		return x.DevInitNanoTime
	}
	return ""
}

func (x *JZRequest) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *JZRequest) GetHardwareModel() string {
	if x != nil {
		return x.HardwareModel
	}
	return ""
}

func (x *JZRequest) GetMemory() int64 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *JZRequest) GetHardDisk() int64 {
	if x != nil {
		return x.HardDisk
	}
	return 0
}

func (x *JZRequest) GetCpuNum() int32 {
	if x != nil {
		return x.CpuNum
	}
	return 0
}

func (x *JZRequest) GetCpuFreq() float64 {
	if x != nil {
		return x.CpuFreq
	}
	return 0
}

func (x *JZRequest) GetIdfaPolicy() int32 {
	if x != nil {
		return x.IdfaPolicy
	}
	return 0
}

func (x *JZRequest) GetBatteryStatus() int32 {
	if x != nil {
		return x.BatteryStatus
	}
	return 0
}

func (x *JZRequest) GetBatteryPower() int32 {
	if x != nil {
		return x.BatteryPower
	}
	return 0
}

func (x *JZRequest) GetDevFileTime() string {
	if x != nil {
		return x.DevFileTime
	}
	return ""
}

func (x *JZRequest) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *JZRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *JZRequest) GetPaid() string {
	if x != nil {
		return x.Paid
	}
	return ""
}

func (x *JZRequest) GetPkgs() []string {
	if x != nil {
		return x.Pkgs
	}
	return nil
}

func (x *JZRequest) GetCaids() []*JZRequest_Caid {
	if x != nil {
		return x.Caids
	}
	return nil
}

type JZResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*JZResult_BidResult  `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JZResult) Reset() {
	*x = JZResult{}
	mi := &file_jiuzhu_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JZResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JZResult) ProtoMessage() {}

func (x *JZResult) ProtoReflect() protoreflect.Message {
	mi := &file_jiuzhu_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JZResult.ProtoReflect.Descriptor instead.
func (*JZResult) Descriptor() ([]byte, []int) {
	return file_jiuzhu_proto_rawDescGZIP(), []int{1}
}

func (x *JZResult) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *JZResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *JZResult) GetData() []*JZResult_BidResult {
	if x != nil {
		return x.Data
	}
	return nil
}

type JZRequest_Caid struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CaidVersion   string                 `protobuf:"bytes,1,opt,name=caid_version,json=caidVersion,proto3" json:"caid_version,omitempty"`
	Caid          string                 `protobuf:"bytes,2,opt,name=caid,proto3" json:"caid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JZRequest_Caid) Reset() {
	*x = JZRequest_Caid{}
	mi := &file_jiuzhu_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JZRequest_Caid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JZRequest_Caid) ProtoMessage() {}

func (x *JZRequest_Caid) ProtoReflect() protoreflect.Message {
	mi := &file_jiuzhu_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JZRequest_Caid.ProtoReflect.Descriptor instead.
func (*JZRequest_Caid) Descriptor() ([]byte, []int) {
	return file_jiuzhu_proto_rawDescGZIP(), []int{0, 0}
}

func (x *JZRequest_Caid) GetCaidVersion() string {
	if x != nil {
		return x.CaidVersion
	}
	return ""
}

func (x *JZRequest_Caid) GetCaid() string {
	if x != nil {
		return x.Caid
	}
	return ""
}

type JZResult_BidResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClkUrl        string                 `protobuf:"bytes,1,opt,name=clk_url,json=clkUrl,proto3" json:"clk_url,omitempty"`
	DpUrl         string                 `protobuf:"bytes,2,opt,name=dp_url,json=dpUrl,proto3" json:"dp_url,omitempty"`
	DpAd          int32                  `protobuf:"varint,3,opt,name=dp_ad,json=dpAd,proto3" json:"dp_ad,omitempty"`
	Mt            int32                  `protobuf:"varint,4,opt,name=mt,proto3" json:"mt,omitempty"`
	Imgs          []string               `protobuf:"bytes,5,rep,name=imgs,proto3" json:"imgs,omitempty"`
	Width         int32                  `protobuf:"varint,6,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,7,opt,name=height,proto3" json:"height,omitempty"`
	Title         string                 `protobuf:"bytes,8,opt,name=title,proto3" json:"title,omitempty"`
	Atx           string                 `protobuf:"bytes,9,opt,name=atx,proto3" json:"atx,omitempty"`
	Pack          string                 `protobuf:"bytes,10,opt,name=pack,proto3" json:"pack,omitempty"`
	Appname       string                 `protobuf:"bytes,11,opt,name=appname,proto3" json:"appname,omitempty"`
	BtTxt         string                 `protobuf:"bytes,12,opt,name=bt_txt,json=btTxt,proto3" json:"bt_txt,omitempty"`
	Act           int32                  `protobuf:"varint,13,opt,name=act,proto3" json:"act,omitempty"`
	BidPrice      int32                  `protobuf:"varint,14,opt,name=bid_price,json=bidPrice,proto3" json:"bid_price,omitempty"`
	ShowTrace     []string               `protobuf:"bytes,15,rep,name=show_trace,json=showTrace,proto3" json:"show_trace,omitempty"`
	ClkTrace      []string               `protobuf:"bytes,16,rep,name=clk_trace,json=clkTrace,proto3" json:"clk_trace,omitempty"`
	DpTryTrace    []string               `protobuf:"bytes,17,rep,name=dp_try_trace,json=dpTryTrace,proto3" json:"dp_try_trace,omitempty"`
	DpSucTrace    []string               `protobuf:"bytes,18,rep,name=dp_suc_trace,json=dpSucTrace,proto3" json:"dp_suc_trace,omitempty"`
	DpFailTrace   []string               `protobuf:"bytes,19,rep,name=dp_fail_trace,json=dpFailTrace,proto3" json:"dp_fail_trace,omitempty"`
	DownTrace     []string               `protobuf:"bytes,20,rep,name=down_trace,json=downTrace,proto3" json:"down_trace,omitempty"`
	DownedTrace   []string               `protobuf:"bytes,21,rep,name=downed_trace,json=downedTrace,proto3" json:"downed_trace,omitempty"`
	InsTrace      []string               `protobuf:"bytes,22,rep,name=ins_trace,json=insTrace,proto3" json:"ins_trace,omitempty"`
	InsedTrace    []string               `protobuf:"bytes,23,rep,name=insed_trace,json=insedTrace,proto3" json:"insed_trace,omitempty"`
	AcTrace       []string               `protobuf:"bytes,24,rep,name=ac_trace,json=acTrace,proto3" json:"ac_trace,omitempty"`
	NoticeTrace   []string               `protobuf:"bytes,25,rep,name=notice_trace,json=noticeTrace,proto3" json:"notice_trace,omitempty"`
	Video         *JZResult_Video        `protobuf:"bytes,26,opt,name=video,proto3" json:"video,omitempty"`
	WxPath        string                 `protobuf:"bytes,27,opt,name=wx_path,json=wxPath,proto3" json:"wx_path,omitempty"`
	WxId          string                 `protobuf:"bytes,28,opt,name=wx_id,json=wxId,proto3" json:"wx_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JZResult_BidResult) Reset() {
	*x = JZResult_BidResult{}
	mi := &file_jiuzhu_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JZResult_BidResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JZResult_BidResult) ProtoMessage() {}

func (x *JZResult_BidResult) ProtoReflect() protoreflect.Message {
	mi := &file_jiuzhu_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JZResult_BidResult.ProtoReflect.Descriptor instead.
func (*JZResult_BidResult) Descriptor() ([]byte, []int) {
	return file_jiuzhu_proto_rawDescGZIP(), []int{1, 0}
}

func (x *JZResult_BidResult) GetClkUrl() string {
	if x != nil {
		return x.ClkUrl
	}
	return ""
}

func (x *JZResult_BidResult) GetDpUrl() string {
	if x != nil {
		return x.DpUrl
	}
	return ""
}

func (x *JZResult_BidResult) GetDpAd() int32 {
	if x != nil {
		return x.DpAd
	}
	return 0
}

func (x *JZResult_BidResult) GetMt() int32 {
	if x != nil {
		return x.Mt
	}
	return 0
}

func (x *JZResult_BidResult) GetImgs() []string {
	if x != nil {
		return x.Imgs
	}
	return nil
}

func (x *JZResult_BidResult) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *JZResult_BidResult) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *JZResult_BidResult) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *JZResult_BidResult) GetAtx() string {
	if x != nil {
		return x.Atx
	}
	return ""
}

func (x *JZResult_BidResult) GetPack() string {
	if x != nil {
		return x.Pack
	}
	return ""
}

func (x *JZResult_BidResult) GetAppname() string {
	if x != nil {
		return x.Appname
	}
	return ""
}

func (x *JZResult_BidResult) GetBtTxt() string {
	if x != nil {
		return x.BtTxt
	}
	return ""
}

func (x *JZResult_BidResult) GetAct() int32 {
	if x != nil {
		return x.Act
	}
	return 0
}

func (x *JZResult_BidResult) GetBidPrice() int32 {
	if x != nil {
		return x.BidPrice
	}
	return 0
}

func (x *JZResult_BidResult) GetShowTrace() []string {
	if x != nil {
		return x.ShowTrace
	}
	return nil
}

func (x *JZResult_BidResult) GetClkTrace() []string {
	if x != nil {
		return x.ClkTrace
	}
	return nil
}

func (x *JZResult_BidResult) GetDpTryTrace() []string {
	if x != nil {
		return x.DpTryTrace
	}
	return nil
}

func (x *JZResult_BidResult) GetDpSucTrace() []string {
	if x != nil {
		return x.DpSucTrace
	}
	return nil
}

func (x *JZResult_BidResult) GetDpFailTrace() []string {
	if x != nil {
		return x.DpFailTrace
	}
	return nil
}

func (x *JZResult_BidResult) GetDownTrace() []string {
	if x != nil {
		return x.DownTrace
	}
	return nil
}

func (x *JZResult_BidResult) GetDownedTrace() []string {
	if x != nil {
		return x.DownedTrace
	}
	return nil
}

func (x *JZResult_BidResult) GetInsTrace() []string {
	if x != nil {
		return x.InsTrace
	}
	return nil
}

func (x *JZResult_BidResult) GetInsedTrace() []string {
	if x != nil {
		return x.InsedTrace
	}
	return nil
}

func (x *JZResult_BidResult) GetAcTrace() []string {
	if x != nil {
		return x.AcTrace
	}
	return nil
}

func (x *JZResult_BidResult) GetNoticeTrace() []string {
	if x != nil {
		return x.NoticeTrace
	}
	return nil
}

func (x *JZResult_BidResult) GetVideo() *JZResult_Video {
	if x != nil {
		return x.Video
	}
	return nil
}

func (x *JZResult_BidResult) GetWxPath() string {
	if x != nil {
		return x.WxPath
	}
	return ""
}

func (x *JZResult_BidResult) GetWxId() string {
	if x != nil {
		return x.WxId
	}
	return ""
}

type JZResult_Video struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Url              string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`                                                      // 视频播放地址
	Duration         int32                  `protobuf:"varint,2,opt,name=duration,proto3" json:"duration,omitempty"`                                           // 视频总时长(秒)
	Format           string                 `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`                                                // 视频格式(mp4/flv等)
	CoverImage       string                 `protobuf:"bytes,4,opt,name=cover_image,json=coverImage,proto3" json:"cover_image,omitempty"`                      // 视频封面图URL
	CoverWidth       int32                  `protobuf:"varint,5,opt,name=cover_width,json=coverWidth,proto3" json:"cover_width,omitempty"`                     // 封面图宽度
	CoverHeight      int32                  `protobuf:"varint,6,opt,name=cover_height,json=coverHeight,proto3" json:"cover_height,omitempty"`                  // 封面图高度
	EndFrameType     int32                  `protobuf:"varint,7,opt,name=end_frame_type,json=endFrameType,proto3" json:"end_frame_type,omitempty"`             // 0:图片 1:HTML
	EndFrameUrl      string                 `protobuf:"bytes,8,opt,name=end_frame_url,json=endFrameUrl,proto3" json:"end_frame_url,omitempty"`                 // 尾帧内容URL
	EndFrameDuration int32                  `protobuf:"varint,9,opt,name=end_frame_duration,json=endFrameDuration,proto3" json:"end_frame_duration,omitempty"` // 尾帧展示时长(秒)
	// 广告应用信息
	AppName     string `protobuf:"bytes,10,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`             // 推广的应用名称
	PackageName string `protobuf:"bytes,11,opt,name=package_name,json=packageName,proto3" json:"package_name,omitempty"` // 应用包名(Android)
	AppLogo     string `protobuf:"bytes,12,opt,name=app_logo,json=appLogo,proto3" json:"app_logo,omitempty"`             // 应用图标URL
	// 交互控制
	SkipTime        int32 `protobuf:"varint,13,opt,name=skip_time,json=skipTime,proto3" json:"skip_time,omitempty"`                      // 可跳过时间(秒)-1表示不可跳过
	AllowMute       bool  `protobuf:"varint,14,opt,name=allow_mute,json=allowMute,proto3" json:"allow_mute,omitempty"`                   // 是否允许静音
	AllowFullscreen bool  `protobuf:"varint,15,opt,name=allow_fullscreen,json=allowFullscreen,proto3" json:"allow_fullscreen,omitempty"` // 是否允许全屏
	// 监测事件
	TrackingEvents []*JZResult_TrackingEvent `protobuf:"bytes,16,rep,name=tracking_events,json=trackingEvents,proto3" json:"tracking_events,omitempty"` //所有监测事件
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *JZResult_Video) Reset() {
	*x = JZResult_Video{}
	mi := &file_jiuzhu_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JZResult_Video) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JZResult_Video) ProtoMessage() {}

func (x *JZResult_Video) ProtoReflect() protoreflect.Message {
	mi := &file_jiuzhu_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JZResult_Video.ProtoReflect.Descriptor instead.
func (*JZResult_Video) Descriptor() ([]byte, []int) {
	return file_jiuzhu_proto_rawDescGZIP(), []int{1, 1}
}

func (x *JZResult_Video) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *JZResult_Video) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *JZResult_Video) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *JZResult_Video) GetCoverImage() string {
	if x != nil {
		return x.CoverImage
	}
	return ""
}

func (x *JZResult_Video) GetCoverWidth() int32 {
	if x != nil {
		return x.CoverWidth
	}
	return 0
}

func (x *JZResult_Video) GetCoverHeight() int32 {
	if x != nil {
		return x.CoverHeight
	}
	return 0
}

func (x *JZResult_Video) GetEndFrameType() int32 {
	if x != nil {
		return x.EndFrameType
	}
	return 0
}

func (x *JZResult_Video) GetEndFrameUrl() string {
	if x != nil {
		return x.EndFrameUrl
	}
	return ""
}

func (x *JZResult_Video) GetEndFrameDuration() int32 {
	if x != nil {
		return x.EndFrameDuration
	}
	return 0
}

func (x *JZResult_Video) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *JZResult_Video) GetPackageName() string {
	if x != nil {
		return x.PackageName
	}
	return ""
}

func (x *JZResult_Video) GetAppLogo() string {
	if x != nil {
		return x.AppLogo
	}
	return ""
}

func (x *JZResult_Video) GetSkipTime() int32 {
	if x != nil {
		return x.SkipTime
	}
	return 0
}

func (x *JZResult_Video) GetAllowMute() bool {
	if x != nil {
		return x.AllowMute
	}
	return false
}

func (x *JZResult_Video) GetAllowFullscreen() bool {
	if x != nil {
		return x.AllowFullscreen
	}
	return false
}

func (x *JZResult_Video) GetTrackingEvents() []*JZResult_TrackingEvent {
	if x != nil {
		return x.TrackingEvents
	}
	return nil
}

// TrackingEvent 消息定义
type JZResult_TrackingEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventType     int32                  `protobuf:"varint,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"` // 事件类型
	TrackUrls     []string               `protobuf:"bytes,2,rep,name=track_urls,json=trackUrls,proto3" json:"track_urls,omitempty"`  // 监测URL列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JZResult_TrackingEvent) Reset() {
	*x = JZResult_TrackingEvent{}
	mi := &file_jiuzhu_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JZResult_TrackingEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JZResult_TrackingEvent) ProtoMessage() {}

func (x *JZResult_TrackingEvent) ProtoReflect() protoreflect.Message {
	mi := &file_jiuzhu_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JZResult_TrackingEvent.ProtoReflect.Descriptor instead.
func (*JZResult_TrackingEvent) Descriptor() ([]byte, []int) {
	return file_jiuzhu_proto_rawDescGZIP(), []int{1, 2}
}

func (x *JZResult_TrackingEvent) GetEventType() int32 {
	if x != nil {
		return x.EventType
	}
	return 0
}

func (x *JZResult_TrackingEvent) GetTrackUrls() []string {
	if x != nil {
		return x.TrackUrls
	}
	return nil
}

var File_jiuzhu_proto protoreflect.FileDescriptor

const file_jiuzhu_proto_rawDesc = "" +
	"\n" +
	"\fjiuzhu.proto\x12\x06jiuzhu\"\xd2\x0f\n" +
	"\tJZRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03ver\x18\x02 \x01(\tR\x03ver\x12\x13\n" +
	"\x05ad_id\x18\x03 \x01(\tR\x04adId\x12\x19\n" +
	"\bad_width\x18\x04 \x01(\x05R\aadWidth\x12\x1b\n" +
	"\tad_height\x18\x05 \x01(\x05R\badHeight\x12\x19\n" +
	"\bapp_name\x18\x06 \x01(\tR\aappName\x12\x19\n" +
	"\bpkg_name\x18\a \x01(\tR\apkgName\x12\x10\n" +
	"\x03apv\x18\b \x01(\tR\x03apv\x12\x12\n" +
	"\x04make\x18\t \x01(\tR\x04make\x12\x14\n" +
	"\x05brand\x18\n" +
	" \x01(\tR\x05brand\x12\x14\n" +
	"\x05model\x18\v \x01(\tR\x05model\x12\x18\n" +
	"\adensity\x18\f \x01(\x01R\adensity\x12\x0e\n" +
	"\x02os\x18\r \x01(\x05R\x02os\x12\x15\n" +
	"\x06os_ver\x18\x0e \x01(\tR\x05osVer\x12\x1b\n" +
	"\tapi_level\x18\x0f \x01(\x05R\bapiLevel\x12\x1b\n" +
	"\tdev_width\x18\x10 \x01(\x05R\bdevWidth\x12\x1d\n" +
	"\n" +
	"dev_height\x18\x11 \x01(\x05R\tdevHeight\x12\x1d\n" +
	"\n" +
	"dev_orient\x18\x12 \x01(\x05R\tdevOrient\x12!\n" +
	"\fappstore_ver\x18\x13 \x01(\tR\vappstoreVer\x12\x18\n" +
	"\ahmscore\x18\x14 \x01(\tR\ahmscore\x12\x15\n" +
	"\x06ui_ver\x18\x15 \x01(\tR\x05uiVer\x12\x19\n" +
	"\bdev_type\x18\x16 \x01(\x05R\adevType\x12\x18\n" +
	"\acarrier\x18\x17 \x01(\x05R\acarrier\x12!\n" +
	"\foperator_nop\x18\x18 \x01(\tR\voperatorNop\x12\x19\n" +
	"\bnet_type\x18\x19 \x01(\x05R\anetType\x12\x12\n" +
	"\x04imsi\x18\x1a \x01(\tR\x04imsi\x12\x10\n" +
	"\x03mac\x18\x1b \x01(\tR\x03mac\x12\x1b\n" +
	"\tbid_price\x18\x1c \x01(\x05R\bbidPrice\x12\x12\n" +
	"\x04imei\x18\x1d \x01(\tR\x04imei\x12\x19\n" +
	"\bimei_md5\x18\x1e \x01(\tR\aimeiMd5\x12\x1d\n" +
	"\n" +
	"android_id\x18\x1f \x01(\tR\tandroidId\x12\x12\n" +
	"\x04oaid\x18  \x01(\tR\x04oaid\x12\x1d\n" +
	"\n" +
	"user_agent\x18! \x01(\tR\tuserAgent\x12\x12\n" +
	"\x04idfa\x18\" \x01(\tR\x04idfa\x12\x19\n" +
	"\bidfa_md5\x18# \x01(\tR\aidfaMd5\x12\x12\n" +
	"\x04idfv\x18$ \x01(\tR\x04idfv\x12\x12\n" +
	"\x04caid\x18% \x01(\tR\x04caid\x12\x19\n" +
	"\bcaid_ver\x18& \x01(\tR\acaidVer\x12\x12\n" +
	"\x04udid\x18' \x01(\tR\x04udid\x12\x0e\n" +
	"\x02ip\x18( \x01(\tR\x02ip\x12\x12\n" +
	"\x04ipv6\x18) \x01(\tR\x04ipv6\x12\x10\n" +
	"\x03ppi\x18* \x01(\x05R\x03ppi\x12\x10\n" +
	"\x03lon\x18+ \x01(\tR\x03lon\x12\x10\n" +
	"\x03lat\x18, \x01(\tR\x03lat\x12\x1b\n" +
	"\tboot_mark\x18- \x01(\tR\bbootMark\x12\x1f\n" +
	"\vupdate_mark\x18. \x01(\tR\n" +
	"updateMark\x12\x1a\n" +
	"\bserialno\x18/ \x01(\tR\bserialno\x12\x17\n" +
	"\arom_ver\x180 \x01(\tR\x06romVer\x12,\n" +
	"\x12sys_compiling_time\x181 \x01(\tR\x10sysCompilingTime\x12 \n" +
	"\fdev_name_md5\x182 \x01(\tR\n" +
	"devNameMd5\x12!\n" +
	"\fstartup_time\x183 \x01(\tR\vstartupTime\x12!\n" +
	"\fupgrade_time\x184 \x01(\tR\vupgradeTime\x122\n" +
	"\x16sys_start_up_nano_time\x185 \x01(\tR\x12sysStartUpNanoTime\x12/\n" +
	"\x14sys_update_nano_time\x186 \x01(\tR\x11sysUpdateNanoTime\x12+\n" +
	"\x12dev_init_nano_time\x187 \x01(\tR\x0fdevInitNanoTime\x12\x1a\n" +
	"\btimezone\x188 \x01(\tR\btimezone\x12%\n" +
	"\x0ehardware_model\x189 \x01(\tR\rhardwareModel\x12\x16\n" +
	"\x06memory\x18: \x01(\x03R\x06memory\x12\x1b\n" +
	"\thard_disk\x18; \x01(\x03R\bhardDisk\x12\x17\n" +
	"\acpu_num\x18< \x01(\x05R\x06cpuNum\x12\x19\n" +
	"\bcpu_freq\x18= \x01(\x01R\acpuFreq\x12\x1f\n" +
	"\vidfa_policy\x18> \x01(\x05R\n" +
	"idfaPolicy\x12%\n" +
	"\x0ebattery_status\x18? \x01(\x05R\rbatteryStatus\x12#\n" +
	"\rbattery_power\x18@ \x01(\x05R\fbatteryPower\x12\"\n" +
	"\rdev_file_time\x18A \x01(\tR\vdevFileTime\x12!\n" +
	"\fcountry_code\x18B \x01(\tR\vcountryCode\x12\x1a\n" +
	"\blanguage\x18C \x01(\tR\blanguage\x12\x12\n" +
	"\x04paid\x18D \x01(\tR\x04paid\x12\x12\n" +
	"\x04pkgs\x18E \x03(\tR\x04pkgs\x12,\n" +
	"\x05caids\x18F \x03(\v2\x16.jiuzhu.JZRequest.CaidR\x05caids\x1a=\n" +
	"\x04Caid\x12!\n" +
	"\fcaid_version\x18\x01 \x01(\tR\vcaidVersion\x12\x12\n" +
	"\x04caid\x18\x02 \x01(\tR\x04caid\"\xec\v\n" +
	"\bJZResult\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12.\n" +
	"\x04data\x18\x03 \x03(\v2\x1a.jiuzhu.JZResult.BidResultR\x04data\x1a\xfc\x05\n" +
	"\tBidResult\x12\x17\n" +
	"\aclk_url\x18\x01 \x01(\tR\x06clkUrl\x12\x15\n" +
	"\x06dp_url\x18\x02 \x01(\tR\x05dpUrl\x12\x13\n" +
	"\x05dp_ad\x18\x03 \x01(\x05R\x04dpAd\x12\x0e\n" +
	"\x02mt\x18\x04 \x01(\x05R\x02mt\x12\x12\n" +
	"\x04imgs\x18\x05 \x03(\tR\x04imgs\x12\x14\n" +
	"\x05width\x18\x06 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\a \x01(\x05R\x06height\x12\x14\n" +
	"\x05title\x18\b \x01(\tR\x05title\x12\x10\n" +
	"\x03atx\x18\t \x01(\tR\x03atx\x12\x12\n" +
	"\x04pack\x18\n" +
	" \x01(\tR\x04pack\x12\x18\n" +
	"\aappname\x18\v \x01(\tR\aappname\x12\x15\n" +
	"\x06bt_txt\x18\f \x01(\tR\x05btTxt\x12\x10\n" +
	"\x03act\x18\r \x01(\x05R\x03act\x12\x1b\n" +
	"\tbid_price\x18\x0e \x01(\x05R\bbidPrice\x12\x1d\n" +
	"\n" +
	"show_trace\x18\x0f \x03(\tR\tshowTrace\x12\x1b\n" +
	"\tclk_trace\x18\x10 \x03(\tR\bclkTrace\x12 \n" +
	"\fdp_try_trace\x18\x11 \x03(\tR\n" +
	"dpTryTrace\x12 \n" +
	"\fdp_suc_trace\x18\x12 \x03(\tR\n" +
	"dpSucTrace\x12\"\n" +
	"\rdp_fail_trace\x18\x13 \x03(\tR\vdpFailTrace\x12\x1d\n" +
	"\n" +
	"down_trace\x18\x14 \x03(\tR\tdownTrace\x12!\n" +
	"\fdowned_trace\x18\x15 \x03(\tR\vdownedTrace\x12\x1b\n" +
	"\tins_trace\x18\x16 \x03(\tR\binsTrace\x12\x1f\n" +
	"\vinsed_trace\x18\x17 \x03(\tR\n" +
	"insedTrace\x12\x19\n" +
	"\bac_trace\x18\x18 \x03(\tR\aacTrace\x12!\n" +
	"\fnotice_trace\x18\x19 \x03(\tR\vnoticeTrace\x12,\n" +
	"\x05video\x18\x1a \x01(\v2\x16.jiuzhu.JZResult.VideoR\x05video\x12\x17\n" +
	"\awx_path\x18\x1b \x01(\tR\x06wxPath\x12\x13\n" +
	"\x05wx_id\x18\x1c \x01(\tR\x04wxId\x1a\xb3\x04\n" +
	"\x05Video\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1a\n" +
	"\bduration\x18\x02 \x01(\x05R\bduration\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format\x12\x1f\n" +
	"\vcover_image\x18\x04 \x01(\tR\n" +
	"coverImage\x12\x1f\n" +
	"\vcover_width\x18\x05 \x01(\x05R\n" +
	"coverWidth\x12!\n" +
	"\fcover_height\x18\x06 \x01(\x05R\vcoverHeight\x12$\n" +
	"\x0eend_frame_type\x18\a \x01(\x05R\fendFrameType\x12\"\n" +
	"\rend_frame_url\x18\b \x01(\tR\vendFrameUrl\x12,\n" +
	"\x12end_frame_duration\x18\t \x01(\x05R\x10endFrameDuration\x12\x19\n" +
	"\bapp_name\x18\n" +
	" \x01(\tR\aappName\x12!\n" +
	"\fpackage_name\x18\v \x01(\tR\vpackageName\x12\x19\n" +
	"\bapp_logo\x18\f \x01(\tR\aappLogo\x12\x1b\n" +
	"\tskip_time\x18\r \x01(\x05R\bskipTime\x12\x1d\n" +
	"\n" +
	"allow_mute\x18\x0e \x01(\bR\tallowMute\x12)\n" +
	"\x10allow_fullscreen\x18\x0f \x01(\bR\x0fallowFullscreen\x12G\n" +
	"\x0ftracking_events\x18\x10 \x03(\v2\x1e.jiuzhu.JZResult.TrackingEventR\x0etrackingEvents\x1aM\n" +
	"\rTrackingEvent\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\x05R\teventType\x12\x1d\n" +
	"\n" +
	"track_urls\x18\x02 \x03(\tR\ttrackUrlsB\vZ\t./;jiuzhub\x06proto3"

var (
	file_jiuzhu_proto_rawDescOnce sync.Once
	file_jiuzhu_proto_rawDescData []byte
)

func file_jiuzhu_proto_rawDescGZIP() []byte {
	file_jiuzhu_proto_rawDescOnce.Do(func() {
		file_jiuzhu_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_jiuzhu_proto_rawDesc), len(file_jiuzhu_proto_rawDesc)))
	})
	return file_jiuzhu_proto_rawDescData
}

var file_jiuzhu_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_jiuzhu_proto_goTypes = []any{
	(*JZRequest)(nil),              // 0: jiuzhu.JZRequest
	(*JZResult)(nil),               // 1: jiuzhu.JZResult
	(*JZRequest_Caid)(nil),         // 2: jiuzhu.JZRequest.Caid
	(*JZResult_BidResult)(nil),     // 3: jiuzhu.JZResult.BidResult
	(*JZResult_Video)(nil),         // 4: jiuzhu.JZResult.Video
	(*JZResult_TrackingEvent)(nil), // 5: jiuzhu.JZResult.TrackingEvent
}
var file_jiuzhu_proto_depIdxs = []int32{
	2, // 0: jiuzhu.JZRequest.caids:type_name -> jiuzhu.JZRequest.Caid
	3, // 1: jiuzhu.JZResult.data:type_name -> jiuzhu.JZResult.BidResult
	4, // 2: jiuzhu.JZResult.BidResult.video:type_name -> jiuzhu.JZResult.Video
	5, // 3: jiuzhu.JZResult.Video.tracking_events:type_name -> jiuzhu.JZResult.TrackingEvent
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_jiuzhu_proto_init() }
func file_jiuzhu_proto_init() {
	if File_jiuzhu_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_jiuzhu_proto_rawDesc), len(file_jiuzhu_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_jiuzhu_proto_goTypes,
		DependencyIndexes: file_jiuzhu_proto_depIdxs,
		MessageInfos:      file_jiuzhu_proto_msgTypes,
	}.Build()
	File_jiuzhu_proto = out.File
	file_jiuzhu_proto_goTypes = nil
	file_jiuzhu_proto_depIdxs = nil
}
